feat: 멤버 미션 API를 작성한다
eom-tae-in/atwoz pull request #21
Opened 2024-03-16 05:53 UTC by devholic22

## 📄 Summary

재윤님이 작성해주신 멤버 미션 API 뼈대를 기반으로 작업하였습니다.

>

## 🙋🏻 More

* 기존 재윤님이 작성해주셨던 `Mission`에 대한 예외들이 `ExceptionHandler`가 없어서 반영하였습니다.
* MemberMission의 earnReward를 보니 doesGetReward를 CLEAR_STATUS로 바꾸는 것 같아, 클리어할 때 doesGetReward도 호출하도록 하였습니다. 혹시 클리어를 하는 것과 미션의 보상을 수령하는 시점이 분리되어야 한다면 수정하도록 하겠습니다.
* 클리어 여부로 조회하는 `MemberMissionsQueryService`의 `findMemberMissionsByStatus` 메서드에서는 페이징을 적용하지 않고 개발하였습니다. 페이징을 필요로 하는 것은 `findMemberMissionsWithPaging`에서만 필요한 것으로 생각하고 개발을 했었는데, 이 또한 페이징을 추가해야 한다면 반영하도록 하겠습니다. (다만, 민호 님께 여쭤보니 회원의 미션을 조회하는 API는 필요하지 않은 영역일수도 있다고 하셨습니다.)
* 쿼리 조회가 사용되는 `MemberMissionsQueryService`는 `MemberMissionRepository`의 메서드가 조회밖에 없고, 저장이 `MemberMissionsRepository`에서 진행되기 때문에 (cascade) `MemberMissionQueryRepositoryTest`를 통합 테스트 하는 방식으로 대체하였습니다.

이번에도 고쳐야 할 점이 있다면 반영하도록 하겠습니다!
> close #19

2024-03-16 12:55 UTC, eom-tae-in requested changes
고생하셨습니다. 몇가지만 수정해주세요~

현준님께서 남겨주신 comment를 보니까 MemberMissionsQueryService를 테스트를 진행하지 않으신거 같은데 해당 service는 테스트를 진행하는 것이 맞아보입니다. service 계층은 실제 구현에 종속되지 않아 mock, fake 객체로 테스트를 진행하기 때문에 테스트를 작성해주시는 것이 맞습니다

2024-03-16 12:55 UTC, eom-tae-in commented on src/main/java/com/atwoz/mission/intrastructure/membermission/MemberMissionQueryRepository.java
> +                .where(memberMission.isStatusClear.eq(isStatusClear))
where절 조건이 여러개인 경우에 ,(comma)로 연결해줄 수 있습니다.

예) where(memberMissions1.memberId.eq(memberId), memberMission.isStatusClear.eq(isStatusClear));
인지들을 매서드로 분리하면 더 좋을 거 같네요!

2024-03-16 12:55 UTC, eom-tae-in commented on src/main/java/com/atwoz/mission/intrastructure/membermission/dto/MemberMissionPagingResponse.java
> +    }
dto에 nextPage를 계산하는 로직이 없어도 될 것 같습니다. 
현재 querydsl을 사용하여 화면에 보여주기 위한 쿼리를 따로 작성중인데 그 작업을 dto에서도 일부 처리하는 것 같아 보입니다.
dto가 데이터를 운반하는 역할만 가지게 하는 것이 좋아보입니다!

2024-03-16 12:55 UTC, eom-tae-in commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsQueryService.java
> +        return memberMissionRepository.findMemberMissionsByStatus(memberId, isStatusClear);
MemberMissionSimpleResponse가 여러 곳에서 사용되는 것으로 파악되는데 화면 출력을 위한 dto는 따로 클래스를 만들어서 반환하는게 어떨까요?
만약 findMemberMissionsByStatus 메서드가 반환하는 데이터의 형식이 바뀌게 된다면 새로운 dto 클래스가 필요하지 않을까요?
클래스를 재사용하기 위해 MemberMissionSimpleResponse를 반환타입으로 사용하신 것 같아보이지만 출력에 해당하는 dto를 따로 생성하면 더 좋을 것 같다는 생각이 듭니다!

2024-03-16 12:55 UTC, eom-tae-in commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsService.java
> +                .orElseThrow(MissionNotFoundException::new);
이 코드도 메서드로 분리하는게 더 좋아보입니다~

2024-03-16 12:55 UTC, eom-tae-in commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsService.java
> +                .orElseGet(() -> createNewMemberMissionsWithMemberId(memberId));
해당 로직을 메서드로 분리하는게 어떨까요?
그리고 orElseGet보다 existByMemberId로 존재하는지 확인하고 없는 경우 생성해주는 방식이 가독성이 더 좋아보입니다!

2024-03-16 13:15 UTC, devholic22 commented on src/main/java/com/atwoz/mission/intrastructure/membermission/MemberMissionQueryRepository.java
> +                .where(memberMission.isStatusClear.eq(isStatusClear))
where절 조건을 콤마로 한 번에 같이 묶을 수 있다는 것은 몰랐네요..! 반영하였습니다

2024-03-16 13:17 UTC, devholic22 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsService.java
> +                .orElseThrow(MissionNotFoundException::new);
수정하였습니다!

2024-03-17 05:21 UTC, sosow0212 requested changes
몇 부분만 확인해주시고 반영해주시면 될 것 같습니다~

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/member/config/AuthConfig.java
> +                .addPathPatterns("/api/members/me/missions/**", ANY);
사용하는 메서드만 열어놓는 게 좋을 것 같아요

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsService.java
> +                .orElseGet(() -> createNewMemberMissionsWithMemberId(memberId));
전 exist도 좋지만 도메인적으로 처리하기 위해서 orElseGet도 괜찮다는 입장이긴합니다

현준님이 직접 둘의 차이를 작성해보면 어떨까요? (성능뿐만 아니라 객체지향적으로 봤을 때)

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMissions.java
> +                .orElseThrow(MemberMissionNotFoundException::new);
예외 메시지를 보면 미션이 아예 없다는 예외를 던지는데 해당 경우에서는 프론트에서 헷갈릴 수 있을 것 같아요
조금 더 명확하게 작성해주는게 좋을 것 같습니다

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/exception/mission/MissionExceptionHandler.java
> +    }
이것도 매개변수에서 HttpStatus를 같이 받는다면 줄일 수 있을 것 같습니다
그리고 e보다는 exception 같은 풀 네이밍을 적는게 좋을 것 같습니다

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMissionRepository.java
> +public interface MemberMissionRepository {
MemberMissionRepository가 필요하나요? OneToMany로 1:N을 가지고 영속상태를 이어가는데 MemberMissions에서 관리되면 되지 않을까요?

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsQueryService.java
> +        Page<MemberMissionSimpleResponse> response = memberMissionRepository.findMemberMissionsWithPaging(memberId, pageable);
MemberMissions를 통해 조회를 해야할 것 같습니다

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/ui/membermission/MemberMissionsController.java
> +    @GetMapping("/all")
해당 로직이 테이블의 값을 조회만 하나요? 이건 GET이 나을까요 POST가 나을까요?

2024-03-17 05:21 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/ui/membermission/MemberMissionsController.java
> +    @GetMapping("/{missionId}")
이것도요

2024-03-17 05:21 UTC, sosow0212 commented on src/test/java/com/atwoz/mission/ui/membermission/MemberMissionsControllerAcceptanceTest.java
> +    class 회원_미션_예외 {
꼼꼼한 검증 굿~

2024-03-17 09:24 UTC, devholic22 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsService.java
> +                .orElseGet(() -> createNewMemberMissionsWithMemberId(memberId));
이 점이 많이 고민되는 점인 것 같습니다.

1만 건의 더미 MemberMissions를 만든 다음 orElseGet과 exists의 방식을 비교해봤는데, 어떤 때는 orElseGet이 더 빠르고 어떤 때는 exists 방식이 더 빠름을 확인했습니다. (격차는 약 200ms 정도였습니다. 테스트를 측정할 때 두 방식 모두 인텔리제이의 캐시를 삭제한 뒤 진행하는 방식으로 했는데, 혹시 더 정확하게 성능을 비교할 수 있는 방법이 있는지도 알아보겠습니다.)

그렇다면 남은 부분은 도메인적, 가독성 부분일 것 같은데 가독성에서는 exists 방식이 "데이터베이스에서 조회했을 때 존재하면 기존 것을 쓰고, 존재하지 않으면 새로 만든다" 느낌을 주므로 (리포지터리 메서드를 직접 작성하므로) 더 나을 것 같다는 생각이 들며,
도메인적으로는 orElseGet이 리포지터리 메서드 반환 타입인 Optional의 특성 (orElseGet)을 이용하고, 없을 때 어떻게 처리를 할 지 하나의 줄에서 바로 명시하므로 더 나을 것 같다는 생각이 들었습니다.

그렇지만 저희가 지향하는 설계는 아무래도 도메인 주도 개발이다보니 재윤님이 말씀하신 orElseGet 방식이 조금 더 맞을 것 같다는 생각이 들었습니다. (그리고 성능이 많이 차이나지 않는다고는 하지만, 이미 MemberMissions가 저장된 경우에는 orElseGet은 바로 select 한 번, exists 방식은 exists -> select로 쿼리가 두 번 호출되기 때문에 select를 한 번만 하는 orElseGet이 조금 더 좋을 것 같다는 생각이 듭니다.)

명확히 어떤 것이 좋다는 결론을 내기 어려운 고민 같은데 이 의견 이후의 태인님의 의견이 궁금합니다!

2024-04-06 06:38 UTC, eom-tae-in reviewed
고생하셨습니다! 몇가지만 수정해주세요:)

2024-04-06 06:38 UTC, eom-tae-in commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsQueryService.java
> +    private static int getNextPage(final int pageNumber, final Page<MemberMissionSimpleResponse> memberMissions) {
static 제거해주세요~

2024-04-06 06:38 UTC, eom-tae-in commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsService.java
> +                .orElseGet(() -> createNewMemberMissionsWithMemberId(memberId));
저도 좀 더 생각해 보니 지금 같은 경우에는 orElseGet으로 처리하는 것이 좋을 거 같습니다!

2024-04-06 06:38 UTC, eom-tae-in commented on src/test/java/com/atwoz/mission/intrastructure/membermission/MemberMissionsFakeRepository.java
> +        id++;
저장되는 id의 값을 1부터 하고 싶어서 이렇게 하신건가요??
그럼 private Long id = 1L;로 하는게 더 나아 보입니다

2024-04-06 07:39 UTC, sosow0212 requested changes
수고하셨습니다 몇 가지만 확인하고 수정해주시면 될 것 같습니다~

2024-04-06 07:39 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsEventHandler.java
> +    public void addClearedMemberMission(final MemberMissionClearedEvent event) {
addedClearMemberMission이 맞을 것 같네요!

2024-04-06 07:39 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMission.java
> +    @ManyToOne(fetch = FetchType.LAZY)
다른 애그리거트인데 해당 방법으로 하신 이유가 있나요
예외가 목적이라면 이벤트로 검증해도 되지 않을까요?

2024-04-06 07:39 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMissions.java
> +    private void validateIsCanAddMission(final Gender memberGender, final Mission mission) {
isCan은 네이밍이 조금 이상한 것 같아요
validateCan~~이 어떨까요?

2024-04-06 07:39 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMissions.java
> +        }
이 부분도 extractChallengeMission 메서드에서 스트림으로 한 번에 할 수 있어보이네요

2024-04-06 07:39 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/intrastructure/membermission/MemberMissionQueryRepository.java
> +    public Page<MemberMissionSimpleResponse> findMemberMissionsWithPaging(final Long memberId, final Pageable pageable) {
해당 쿼리는 어떻게 나갈까요?

2024-04-06 07:39 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsService.java
> +    private final MissionRepository missionRepository;
MemberMission 쪽이 모두 Mission에 영향을 받을 거 같은데 Mission 참조는 없어도 될 것 같습니다 이벤트나 다른 걸로 풀어나가면 어떨까요?

2024-04-07 05:55 UTC, devholic22 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsEventHandler.java
> +    public void addClearedMemberMission(final MemberMissionClearedEvent event) {
clear에만 과거형을 붙였었네요 수정 완료하였습니다!

2024-04-07 05:55 UTC, devholic22 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMissions.java
> +    private void validateIsCanAddMission(final Gender memberGender, final Mission mission) {
수정하였습니다! is can 둘 다 동사였는데 함께 사용했었네요

2024-04-07 05:57 UTC, devholic22 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMissions.java
> +        }
ifPresent를 이용하여 수정하였습니다!

2024-04-07 05:57 UTC, devholic22 commented on src/test/java/com/atwoz/mission/intrastructure/membermission/MemberMissionsFakeRepository.java
> +        id++;
수정하였습니다!

2024-04-07 05:57 UTC, devholic22 commented on src/main/java/com/atwoz/mission/application/membermission/MemberMissionsQueryService.java
> +    private static int getNextPage(final int pageNumber, final Page<MemberMissionSimpleResponse> memberMissions) {
제거 완료하였습니다 :)

2024-04-07 06:08 UTC, devholic22 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMission.java
> +    @ManyToOne(fetch = FetchType.LAZY)
MemberMission에서 보상을 수령할 때 미션으로부터 받게 되고, 회원이 가지고 있는 미션이 챌린지 미션인지를 판단하는 과정에서도 미션으로부터 메서드를 호출하게 됩니다.
또한, MemberMission이 미션에 대한 id만 가지고 있다면 MemberMission을 조회할 때 제약이 너무 많이 생길 것 같다는 생각이 들었습니다. (챌린지/데일리 여부, 미션의 보상 등등)
그래서 서로 다른 애그리거트더라도, 이 경우에 대해서는 객체 참조로 하는 게 적절할 것 같다는 판단을 하였습니다.

이벤트 방식으로 하면 `이벤트를 수신한 객체로부터 값을 전달받는 것`에 대해 제약이 많을 것 같은데, 재윤님께서는 이러한 상황에서 어떻게 해결하시는지 여쭤봐도 될까요?

2024-04-08 06:36 UTC, sosow0212 commented on src/main/java/com/atwoz/mission/domain/membermission/MemberMission.java
> +    @ManyToOne(fetch = FetchType.LAZY)
음 이 부분은 생성할 때 역정규화로 값을 저장해도 될 것 같아요
조금 어색하게 느껴지는데 일단 현준님 말도 충분히 이해는 돼서 개발하다가 문제가 생기면 그때 바꾸는 걸로 하도록 합시다!

2024-04-08 06:36 UTC, sosow0212 approved these changes
작업하시느라 수고하셨습니다.

2024-04-08 06:44 UTC, eom-tae-in approved these changes

2024-04-08 06:46 UTC, merged