refactor: Member 리팩토링
eom-tae-in/atwoz pull request #23
Opened 2024-04-02 05:32 UTC by eom-tae-in

## 📄 Summary

 Member 전반적인 구조를 리팩토링하였습니다.

## 🙋🏻 More

- member 바운디드 컨텍스트 안에 profile이 존재한다고 판단하여 info 패키지에 구현되어있던 모든 프로필 정보를 member 루트 엔티티가 관리하도록 변경했습니다.
- softDelete를 member에 적용하기 위해 BaseEntity를 상속받아 delete_at 필드를 추가한 SoftDeleteBaseEntity를 구현하였습니다.

2024-04-02 10:46 UTC, sosow0212 commented on src/main/java/com/atwoz/global/domain/SoftDeleteBaseEntity.java
> +public abstract class SoftDeleteBaseEntity extends BaseEntity {
소프트 딜리트 좋습니다 👍

2024-04-02 11:38 UTC, sosow0212 approved these changes
리팩토링 하는 것이 엄청 힘들었을텐데 깔끔하게 잘 해주셔서 훨씬 보기 좋아졌습니다.

너무 고생하셨고 수고 많이하셨습니다 !!
코멘트 단 거 몇 부분만 확인해주시고 Merge 시켜도 될 것 같습니다 :)

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/member/profile/physical_profile/Gender.java
> -package com.atwoz.member.domain.info.profile.body;
이건 사소한 부분인데요~ profile.physicalprofile 이라는 네이밍으로 패키징 이름을 변경하는 건 어떨까요?
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

혹은 이미 profile이 상단에 위치하니 physical이라고 해도 좋을 것 같습니다!

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/member/MemberProfile.java
> +
불필요한 공백!

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/member/MemberProfile.java
> +    private ProfileAccessStatus profileAccessStatus;
TODO: 상태 변경해주는 메서드 추가

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/infrastructure/member/MemberJpaRepository.java
> +
인터페이스에서 매개변수에 final은 모두 없어도 될 것 같습니다!

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/auth/interceptor/LoginValidCheckerInterceptor.java
> +        Member foundMember = memberRepository.findByPhoneNumber(memberPhoneNumber)
멤버를 찾고 id를 다시 넣어주는 것보다는 토큰에 들어온 id를 사용하고, 추후에 예외를 다루는 건 어떨까요?

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/auth/interceptor/LoginValidCheckerInterceptor.java
> +        Member foundMember = memberRepository.findByPhoneNumber(memberPhoneNumber)
PASS 때문이라면, 요청별로 다르게 인증하는 건 어떨까요? 현재는 무조건 member를 조회하는 것 같습니다

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +    public void create(final String phoneNumber) {
가입이 됐다면 이미 가입됐다고 예외하나 던져주면 사용자 입장에서는 무반응일 수 있으니 프론트에서 예외를 받아서 처리하면 좋을 것 같습니다!

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +            validateNicknameExists(recommender);
가독성이 조금 더 좋았으면 좋겠습니다.
디스코드에서 말한 것처럼 하면 더 좋을 것 같습니다!

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +    public void updateMember(final Long memberId, final MemberUpdateRequest memberUpdateRequest) {
foundMember를 찾고,
foundMember.update(...) 를 하고 객체 안에서 검증을 하면 어떨까요?

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/member/Member.java
> +@SQLRestriction("deleted_at is null")
👍

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/member/Member.java
> +@SQLRestriction("deleted_at is null")
@Unique를 달면 어떨까요? 그리고 추후에 column 정보는 얘기해보고 정해봅시다!

2024-04-02 11:38 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/member/Member.java
> +    private String recommender;
recommenderId로 간접참조를 한다면 닉네임 조회할 때 정합성 문제가 생기지 않을 것 같습니다!

2024-04-02 11:38 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/member/MemberServiceTest.java
> +            softly.assertThat(member.isPresent()).isTrue();
-> `softly.assertThat(member).isPresent();`

2024-04-02 11:38 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/member/MemberServiceTest.java
> +    @Nested
👍

2024-04-02 11:38 UTC, sosow0212 commented on src/test/java/com/atwoz/member/ui/member/MemberControllerAcceptanceTest.java
> +        토큰 = 토큰_생성(회원_생성());
중복되는 부분이라서 @BeforeEach에 빼는 것이 좋을 것 같습니다!

2024-04-02 11:38 UTC, sosow0212 commented on src/test/java/com/atwoz/member/ui/member/MemberControllerWebMvcTest.java
> +class MemberControllerWebMvcTest extends MockBeanInjection {
REST Docs 추가가 안 되어있습니다!

++ 조회 기능도 구현해야합니다! (TODO: 이슈 분리해서 따로 하면 될듯 합니다.)

2024-04-08 07:45 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/infrastructure/member/MemberJpaRepository.java
> +
수정하겠습니다!

2024-04-08 12:00 UTC, devholic22 requested changes
많은 작업 하시느라 고생하셨습니다! 사소한 것들만 고쳐주시면 좋을 것 같습니다.

개인적으로 궁금한 점이 있는데,
1. 테스트를 진행할 때 `@Nested`일 경우 `@DisplayName`을 사용하신 것을 보았습니다. 클래스다보니 클래스 형식에 맞추어 영문으로 하기 위해 그러신 것 같은데, 재윤 님과 저는 그동안 `@Nested`일 때도 한글로 작성했었습니다. 이 부분을 서로 한 방식으로 맞춰보면 좋을 것 같습니다.
2. 간혹 메서드에서 바로 리턴을 할 때, 메서드 선언과 리턴 부분에 공백을 넣으신 경우가 있는데 특별한 의도가 있으셔서 그랬던 것인지 궁금합니다!

2024-04-08 12:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +    private void validateNicknameIsUnique(final String nickname) {
사소한 것이긴 한데, validateNicknameIsUnique보다는 validateIsNicknameUnique가 더 적절할 것 같은데 어떠실까요?

2024-04-08 12:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +        validateRecommenderNickname(memberInitializeRequest.recommender());
memberInitializeRequest의 속성에 대한 값들을 검증하는데, 만약 요구사항이 바뀌어 추가적으로 다른 속성도 검사할 필요가 있을 수 있으니 validateNicknameIsUnique, validateRecommenderNickname을 하나의 메서드에서 호출하는 것은 어떨까요?
ex: validateMemberInitializeRequestProperties(memberInitializeRequest)

2024-04-08 12:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/config/AuthConfig.java
> +                .addPathPatterns("/api/members/**", ANY);
/api/members/ 도 사용하는 메서드에 대해서만 작성하는 게 좋을 것 같습니다!

2024-04-08 12:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/member/Member.java
> +
createWithOAuth, createWithPass 메서드에서 첫 줄 공백을 붙이신 이유가 있으실까요?

2024-04-08 12:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/member/MemberStatus.java
> +    HUMAN("휴먼"),
혹시 휴먼이 휴면 상태인 것을 의도하셨던 것일까요? 활동중, 임시 정지, 영구 정지 상태는 이해가 되는데 휴먼이 나와서 질문드립니다!

2024-04-08 12:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/member/dto/MemberProfileInfo.java
> +
createWith 메서드들에서 공백 제거하면 좋을 것 같습니다!

2024-04-08 12:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/member/profile/Location.java
> +    public Location(final String city, final String sector) {
`@AllArgsConstructor`로 축약할 수 있을 것 같습니다!

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/domain/profile/DrinkTest.java
> +
불필요한 공백 같습니다!

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/domain/profile/HobbyTest.java
> +
불필요한 공백 같습니다

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/ui/member/MemberControllerAcceptanceFixture.java
> +
이 부분도 특별한 이유가 없다면 공백을 없애는 게 좋을 것 같습니다!

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/infrastructure/member/MemberJpaRepositoryTest.java
> +        // then
when / then 사이 공백 있어야 할 것 같습니다 :)

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/infrastructure/member/MemberJpaRepositoryTest.java
> +    @DisplayName("회원를 찾는다")
`회원을 찾는다`로 표현하는 게 맞을 것 같습니다 :)

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/infrastructure/member/MemberFakeRepository.java
> +        map.put(id++, member);
다른 FakeRepository처럼 id가 1부터 진행되면 좋을 것 같습니다!

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/fixture/domain/member/MemberProfileInfoFixture.java
> +
공백 없애주시면 좋을 것 같습니다 :)

2024-04-08 12:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/domain/profile/physical_profile/GenderTest.java
> +
불필요한 공백이 있습니다!

2024-04-14 04:51 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/ui/auth/interceptor/LoginValidCheckerInterceptor.java
> +        Member foundMember = memberRepository.findByPhoneNumber(memberPhoneNumber)
말씀해주신대로 지금은 무조건 member를 조회하고 있습니다.

PASS 인증을 하게 되면 phoneNumber로 회원이 생성되고 phoneNumber로 암호화한 토큰을 응답으로 주게 되는데 이 uri의 응답 을 postHandle로 잡아서 phoneNumber로 암호화 된 토큰을 가지고 member를 찾아 member의 id값으로 다시 토큰을 생성하여 응답 body에 넣어주는 방식으로 리팩토링을 진행하였습니다.

이렇게 할 경우 회원 검증이 필요한 uri에는 항상 token에서 id 정보로 유효한 요청인지 확인만 하면 됩니다.

과정을 좀 더 자세히 설명드리면 다음과 같습니다.

PASS 인증 진행 -> PASS 인증 완료 -> 회원 생성(with phoneNumber) -> phoneNumber로 토큰 생성 -> PASS 인증 요청 uri를 interceptor에 추가하여 postHandle로 잡음 -> postHandle로 phoneNumber로 암호화한 토큰을 response에서 꺼냄 -> phoneNumber로 Member를 찾은 후 Member id로 토큰을 재생성함 -> 재생성한 토큰은 response body에 넣음

이렇게 해서 응답으로 넘겨지게 되는 토큰은 phoneNumber로 암호화한 토큰이 아니라 id로 암호화한 토큰이 넘어가게 되고 로그인 검증이 필요한 요청은 id로 토큰이 유효한지 검증을 하면 되도록 구현하였습니다.

2024-04-14 05:11 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/member/Member.java
> +    private String recommender;
닉네임이 변경이 가능하기 때문에 말씀해주신 대로 간접 참조 방법으로 바꾸는게 좋을 거 같네요 :)

2024-04-14 06:30 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +    private void validateNicknameIsUnique(final String nickname) {
validateNicknameIsUnique가 직관적으로 이해하기 편해보여서 작성하였는데 validateIsNicknameUnique가 올바른 문법인가요?
validateIsNicknameUnique가 적절하다고 생각하신 이유가 궁금하네요!

2024-04-14 06:44 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +        validateRecommenderNickname(memberInitializeRequest.recommender());
다른 속성 검증이라면 어떤 것이 있을까요?
프로필 정보들을 검증하는 것을 프로필 엔티티나 VO 클래스에서 진행하고 있기 때문에 repository를 통해 검증이 가능한 것들만 validation을 진행하면 된다고 파악했습니다. 혹시 제가 놓친 부분이 있다면 추가로 의견 달아주시면 감사하겠습니다 :)

2024-04-14 06:44 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/config/AuthConfig.java
> +                .addPathPatterns("/api/members/**", ANY);
네 수정하겠습니다!

2024-04-14 06:49 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/member/Member.java
> +
가독성 좋게 만들려고 공백을 추가했던것 같습니다 ㅎㅎ
저희 프로젝트 컨벤션에는 맞지 않으니 공백 제거하겠습니다!

2024-04-14 06:52 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/member/MemberStatus.java
> +    HUMAN("휴먼"),
네 맞습니다! 휴먼  상태를 의미하는 것이 맞습니다.

2024-04-14 06:53 UTC, eom-tae-in commented on src/test/java/com/atwoz/member/infrastructure/member/MemberJpaRepositoryTest.java
> +        // then
추가하겠습니다!

2024-04-14 06:54 UTC, eom-tae-in commented on src/test/java/com/atwoz/member/infrastructure/member/MemberFakeRepository.java
> +        map.put(id++, member);
네 수정하겠습니다!

2024-04-14 07:41 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +    public void updateMember(final Long memberId, final MemberUpdateRequest memberUpdateRequest) {
validateUpdateNickname() 메서드는 member 객체 안에서 처리해야하는 로직이네요!
좋은 지적 감사합니다 :)

2024-04-14 07:51 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +    public void create(final String phoneNumber) {
네 알겠습니다!

2024-04-14 07:52 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +    private void validateNicknameIsUnique(final String nickname) {
저는 boolean, void (validate) 함수의 네이밍에 대해서는 주로 질의하는 형식의 문법을 사용하는 편이라, 특별한 경우를 제외하고는 ~~isA? 이런 식으로 메서드를 작성하고 있습니다. ([참고 글](https://soojin.ro/blog/naming-boolean-variables))
하지만 더 생각해보니 validateNicknameIsUnique도 의미가 충분히 전달되기는 한 것 같네요 ㅎㅎ 만약 기존에 작성하신 게 더 직관적으로 느껴지신다면 수정하지 않으셔도 무방할 듯 합니다!

2024-04-14 07:53 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/member/MemberProfile.java
> +    private ProfileAccessStatus profileAccessStatus;
추가했습니다!

2024-04-14 07:59 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +        validateRecommenderNickname(memberInitializeRequest.recommender());
memberInitializeRequest의 속성을 보면 profileInitializeRequest, nickname, recommender가 있는데, 만약 nickname과 recommender 이외의 추가적인 String 등이 memberInitializeRequest에 들어간다면 그 속성에 대해서도 validate 하는 과정이 지금의 validateNicknameIsUnique, validateRecommenderNickname처럼 필요할 것이라 생각됩니다.

저는 validate할 게 두 개 이상일 경우 그것들을 가지고 있는 클래스 (여기에서는 memberInitializeRequest)를 이용하여 하나의 validate메서드를 만든 다음 세부적으로 validate 메서드들을 호출하는 편인데, 태인 님께서는 어떻게 생각하시는지 궁금합니다!

2024-04-14 08:02 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/member/MemberStatus.java
> +    HUMAN("휴먼"),
그렇다면 `HUMAN("휴먼")` 보다는 `SLEEP("휴면")`이 더 의미에 부합하지 않을까 생각됩니다. 휴먼은 사람 상태 (?)를 의미하는 것 같아서 저희의 요구사항에는 `SLEEP("휴면")` (계정 일시 정지)이 맞다고 생각하는데 어떠실까요?

2024-04-14 08:09 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +        validateRecommenderNickname(memberInitializeRequest.recommender());
해당 메서드 내부에서 한 속성에 대한 validate 메서드를 여러개 사용하는 것 보다 memberInitializeRequest에 대한 validate를 관리하는 메서드를 호출해서 내부적으로 각각의 속성에 대한 validate 메서드를 호출하는 방식을 이야기 해주신거 같네요

현준님 말씀대로 기존의 로직처럼 각 속성에 대한 validate를 한다면 각 속성에 대한 validate를 관리하는 메서드를 통해 구현하는 것이 좋다고 생각합니다! 하지만 지금은 기존 recommender 정보를 닉네임으로 entity에 저장하지 않고 id로 저장하여 간접 참조를 하는 방식으로 리팩토링을 하여 recommender에 대해서는 validate를 함과 동이에 Long 타입을 반환해야 하는 상황입니다.
(간접 참조하는 방식으로 변경한 이유는 닉네임이 변경이 가능하여서 닉네임을 추적을 해야하기 때문에 변경했습니다.)
그래서 validate 메서드를 하나로 묶는 메서드는 지금으로써는 크게 이점이 없다고 생각이 됩니다.
추가적인 의견 있으시면 편하게 말씀해주세요 :)

2024-04-14 09:06 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/member/MemberStatus.java
> +    HUMAN("휴먼"),
의미상 휴면도 괜찮네요 :) 
ACTIVE와 상반되는 INACTIVE로 하여 INACTIVE("휴면")으로 하면 좋을거 같습니다!

2024-04-14 09:46 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/member/MemberService.java
> +        validateRecommenderNickname(memberInitializeRequest.recommender());
말씀하신 내용을 보니 크게 속성이 추가되지는 않을 것 같다는 생각이 들었습니다! 그대로 진행해주셔도 될 것 같습니다 :)

2024-04-14 09:46 UTC, devholic22 approved these changes

2024-04-15 11:45 UTC, merged