feat: 연애 모의고사를 작성한다
eom-tae-in/atwoz pull request #28
Opened 2024-05-16 11:33 UTC by devholic22

## 📄 Summary

연애 모의고사와 관련된 기능을 개발하였습니다.

* 관리자는 연애 모의고사를 등록할 수 있습니다.
  * 기획 요구사항을 반영하여, MVP 단계에서는 생성만 가능하도록 하였습니다.
  * 연애 모의고사는 과목 : 질문 : 답변 = 1 : N : 1의 구조를 가집니다. 각 과목은 여러 질문을 생성하며, 각 질문은 여러 답변을 생성하도록 했기 때문에 생명주기가 종속된다고 생각해 OneToMany를 이용하였습니다. 또한, 답변을 구분할 때는 answerNumber (1번, 2번, 3번 등 선택지 번호)를 두도록 하였습니다.
* 회원은 연애 모의고사를 응시할 수 있습니다.
  * 없는 연애과목을 등록하거나, 같은 질문에 중복되게 제출하거나, 없는 답변 번호를 작성할 때 예외가 발생하도록 하였습니다.
* 회원과 같은 과목, 같은 질문, 같은 답변을 30개 이상 작성한 회원 목록을 추출 (매칭)할 수 있도록 하였습니다. 다만 이 부분은 쿼리가 최적화되지 않은 것 같습니다.

## 🙋🏻 More
* OneToMany + JoinColumn으로 구조를 설계하다보니 매칭에서 조인할 때, 질문 (SurveyAnswer)이 속한 과목 (Survey)을 데이터베이스에서는 알고 있지만, 자바 코드에서는 모르게 되는 문제가 있어 Querydsl을 쓰지 않고 JdbcTemplate을 쓰도록 하였습니다. 이 부분이 적절한 해결 방법일지 의견을 나눠보고 싶습니다.

2024-05-17 03:23 UTC, eom-tae-in requested changes
고생하셨습니다~ 몇가지 수정해주세요

2024-05-17 03:23 UTC, eom-tae-in commented on src/main/java/com/atwoz/survey/domain/survey/Survey.java
> +    private static void validateIsQuestionsNotDuplicated(final List<SurveyQuestionCreateRequest> questionRequests) {
1. validate도 동사고 is도 동사인데 둘을 같이 사용하신 이유가 있나요?
2. 해당 메서드를 타입 변환을 담당하는 메서드와 검증을 하는 메서드로 분리해서 사용하는 건 어떨까요?

2024-05-17 03:23 UTC, eom-tae-in commented on src/main/java/com/atwoz/survey/domain/survey/Survey.java
> +    public static Survey from(final SurveyCreateRequest request) {
SurveyCreateRequest는 ui계층에서 사용하는 dto인 것으로 파악되는데 entity에서 dto로 받지 않고 필드 값으로 받는건 어떨까요?

2024-05-17 03:23 UTC, eom-tae-in commented on src/main/java/com/atwoz/survey/application/membersurvey/MemberSurveysService.java
> +    }
해당 메서드 로직을 분리하는게 좋아보입니다!

2024-05-17 03:23 UTC, eom-tae-in commented on src/main/java/com/atwoz/survey/application/membersurvey/MemberSurveysService.java
> +        return memberSurveys;
return memberSurveysRepository.save(memberSurveys); 로 바꾸면 좋을거 같아요 :)

2024-05-17 03:23 UTC, eom-tae-in commented on src/main/java/com/atwoz/survey/domain/survey/SurveyQuestion.java
> +    private boolean isContainsSameAnswer(final Integer answerNumber) {
is, contains 모두 동사인데 hasSameAnswer로 바꾸는 건 어떨까요?

2024-05-17 03:23 UTC, eom-tae-in commented on src/main/java/com/atwoz/survey/domain/membersurvey/MemberSurveys.java
> +    public void submitSurveys(final List<SurveySubmitRequest> requests) {
SurveySubmitRequest는 ui 계층에서 요청을 받는 dto로 사용되고 있는데 entity에서 파라미터로 받는 게 괜찮을까요? 이렇게 사용하신 이유가 있나요?

2024-05-19 13:51 UTC, devholic22 commented on src/main/java/com/atwoz/survey/domain/survey/Survey.java
> +    private static void validateIsQuestionsNotDuplicated(final List<SurveyQuestionCreateRequest> questionRequests) {
검증 메서드를 작성할 때 간혹 의문사로 작성하는 습관이 아직 있는 것 같네요..! 다른 메서드들도 반영하였습니다.
메서드 분리는 다른 코멘트에서 작성하겠습니다!

2024-05-19 13:53 UTC, devholic22 commented on src/main/java/com/atwoz/survey/domain/survey/Survey.java
> +    public static Survey from(final SurveyCreateRequest request) {
도메인 단에 dto 패키지를 두고 그 dto에서 서비스 -> 도메인으로 변환되는 방식으로 수정하였습니다. 처음 의도는 dto 안에 세부 dto가 있어 복잡할 것 같아 서비스 dto를 받도록 했는데 의존을 최대한 덜어내야 하는 것을 잊고 있었네요. 감사합니다!

2024-05-19 13:53 UTC, devholic22 commented on src/main/java/com/atwoz/survey/application/membersurvey/MemberSurveysService.java
> +        return memberSurveys;
인라인 변수로 수정 완료하였습니다 :)

2024-05-19 13:53 UTC, devholic22 commented on src/main/java/com/atwoz/survey/domain/survey/SurveyQuestion.java
> +    private boolean isContainsSameAnswer(final Integer answerNumber) {
수정 완료하였습니다!

2024-05-19 13:53 UTC, devholic22 commented on src/main/java/com/atwoz/survey/domain/membersurvey/MemberSurveys.java
> +    public void submitSurveys(final List<SurveySubmitRequest> requests) {
도메인 단에 dto를 두는 것으로 수정하였습니다!

2024-05-19 13:56 UTC, devholic22 commented on src/main/java/com/atwoz/survey/application/membersurvey/MemberSurveysService.java
> +    }
수정 완료하였습니다!

2024-05-21 00:00 UTC, eom-tae-in approved these changes

2024-05-21 00:56 UTC, merged