feat: 호감 기능을 구현한다
eom-tae-in/atwoz pull request #33
Opened 2024-06-20 09:18 UTC by devholic22

## 📄 Summary

호감 전송, 조회 기능을 완료했습니다.

## 🙋🏻 More
호감은 보낸 회원의 id, 받은 회원의 id, 호감 정도 (LikeLevel), 호감 아이콘 (LikeIcon), 최근 여부 (isRecent)로 구성되어 있습니다.

### 호감 전송
* 호감을 전송하기 전, 보내는 회원과 받는 회원이 있는지 검증합니다. 또 `ValidatedMemberExistEvent`를 멤버 도메인에 전달하여, 받는 회원이 존재하는 회원인지도 검증합니다.
* 호감을 전송할 때는 전송 직후이므로 isRecent가 true로 되어 있으며, 호감 아이콘은 아무런 아이콘이 나오지 않는 상태이기 때문에 기본값을 적용했습니다.
* 이미 호감이 존재하는 경우에는 (48시간 삭제 참고) 보낼 수 없습니다.

### 호감 조회
* 호감을 조회할 때는 모두 최근에 받거나 보낸 것이 먼저 나오도록 구성하였습니다.
* 조회 부분과 관련한 쿼리 로직이 아직 비효울적인 것 같습니다. 리뷰 후 개선점을 고민해 보겠습니다.

### 기타
* 30일이 지나도 호감 이외의 메시지나 매칭을 받지 못했을 경우 (아이콘이 계속 기본값인 경우)에는 호감이 삭제됩니다.
* 48시간 (이틀) 뒤에는 회원의 최근 여부가 false로 됩니다.
* 위 스케줄 메서드들은 모두 자정 단위로 실행되게끔 하였습니다.
* 호감 아이콘을 변경하는 행위는 호감 기능만으로는 불가능하고 메시지 (연락), 매칭 등의 다른 도메인이 연계되어 이벤트로써 활용할 수 있을 것 같다고 생각해 메서드 껍데기만 작성해두었습니다. 이 점 참고해주시면 좋을 것 같습니다.

2024-06-20 11:12 UTC, eom-tae-in requested changes
고생하셨습니다. 몇가지만 수정해주세요~

2024-06-20 11:12 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/member/event/ValidatedMemberExistEvent.java
> +public record ValidatedMemberExistEvent(
exist는 동사인데 클래스 이름으로는 명사인 existence가 더 적합해보입니다 :)

2024-06-20 11:12 UTC, eom-tae-in commented on src/main/java/com/atwoz/memberlike/infrastructure/MemberLikeQueryRepository.java
> +    }
쿼리 dsl로 조회할 때 offset, limit로 페이징해서 조회하는게 좋아보이는데 이렇게 구현하신 이유가 있나요?

2024-06-20 11:12 UTC, eom-tae-in commented on src/main/java/com/atwoz/memberlike/ui/MemberLikeController.java
> +    @GetMapping("/send")
restful convention에 맞게 sending으로 바꾸면 좋을 것 같습니다 :)

2024-06-20 11:12 UTC, eom-tae-in commented on src/test/java/com/atwoz/memberlike/domain/MemberLikeTest.java
> +    }
이 테스트 메서드들도 @Nested안에 포함시켜도 되지 않을까요?

2024-06-20 11:12 UTC, eom-tae-in commented on src/test/java/com/atwoz/memberlike/infrastructure/MemberLikeFakeRepository.java
> +    }
final 키워드 붙여주세요~

2024-06-20 11:12 UTC, eom-tae-in commented on src/test/java/com/atwoz/memberlike/infrastructure/MemberLikeJdbcRepositoryTest.java
> +        LocalDateTime pastTime = LocalDateTime.now().minusDays(MINUS_DAY_FOR_DELETE_NOT_ANSWERED_LIKE);
체이닝이 2개네요 줄바꿈 부탁드려요~

2024-06-20 11:12 UTC, eom-tae-in commented on src/test/java/com/atwoz/memberlike/infrastructure/MemberLikeQueryRepositoryTest.java
> +                .toList();
자주 나오는 로직인거 같은데 메서드 분리하는게 좋아보여요

2024-06-20 11:12 UTC, eom-tae-in commented on src/main/java/com/atwoz/memberlike/domain/MemberLike.java
> +    }
LikeLevel에 대한 검증을 진행해야하지 않을까요?

2024-06-20 11:12 UTC, eom-tae-in commented on src/main/java/com/atwoz/memberlike/domain/MemberLike.java
> +    }
이 부분도 검증이 필요해보입니다!

2024-06-20 12:52 UTC, devholic22 commented on src/main/java/com/atwoz/memberlike/domain/MemberLike.java
> +    }
`updateLikeIcon`은 상대가 메시지를 보내거나, 서로 매칭이 성사될 때 이벤트를 통해 해당 호감 엔티티의 상태를 바꾸도록 만들 계획입니다. 그런 점에서 이벤트를 제외하고는 해당 메서드를 쓸 일이 없다고 판단하여 String 타입으로 받기보다는 직접적인 `LikeIcon.HEART` 등으로 이벤트 코드에서 작성할 생각이었는데 어떻게 생각하시는지 궁금합니다!

2024-06-20 12:52 UTC, devholic22 commented on src/main/java/com/atwoz/memberlike/domain/MemberLike.java
> +    }
LikeLevel에 대한 검증은 정적 팩터리 메서드에서 생성할 때 `LikeLevel.findByName`을 통해 검증하고 있는데, 혹시 다른 검증을 의미하신 것일까요?

2024-06-20 12:52 UTC, devholic22 commented on src/main/java/com/atwoz/memberlike/ui/MemberLikeController.java
> +    @GetMapping("/send")
Restful 원칙에 대해 다시 생각해 본 결과, send와 receive 모두 동사 형태로 현재 적합하지 않은 형태라는 것을 느꼈습니다.
그러나 말씀해주신 sending 또한 동명사 형태긴 하지만 현재 진행중인 느낌이 강한 것 같아 대신 `likes/sent`, `likes/received` 등 수동태 느낌이 나도록 수정 완료하였습니다! 짚어주셔서 감사합니다 :)

2024-06-20 12:52 UTC, devholic22 commented on src/test/java/com/atwoz/memberlike/domain/MemberLikeTest.java
> +    }
거의 항상 예외 단에서만 nested를 적용했는데 정상인 경우에도 가짓수가 늘어난다면 nested를 적용하는 게 가독성 측면에서 좋은 걸 느꼈습니다 :) 적용 완료했습니다!

2024-06-20 12:52 UTC, devholic22 commented on src/test/java/com/atwoz/memberlike/infrastructure/MemberLikeJdbcRepositoryTest.java
> +        LocalDateTime pastTime = LocalDateTime.now().minusDays(MINUS_DAY_FOR_DELETE_NOT_ANSWERED_LIKE);
수정하였습니다 :)

2024-06-20 12:52 UTC, devholic22 commented on src/test/java/com/atwoz/memberlike/infrastructure/MemberLikeQueryRepositoryTest.java
> +                .toList();
테스트 코드에서는 메서드 분리를 도입하지 않았었는데 테스트 코드에서도 반복된다면 메서드 분리를 도입하는 게 가독성이 좋아진다는 걸 느꼈습니다 :) 메서드 추출 후 적용하였습니다

2024-06-20 12:52 UTC, devholic22 commented on src/main/java/com/atwoz/memberlike/infrastructure/MemberLikeQueryRepository.java
> +    }
톡으로 전달한 내용을 PR에서도 작성하면 좋을 것 같아 재작성 하겠습니다!

MemberLikeQueryRepository에서 현재 구현할 때는 쿼리 매핑으로 한 번에 응답 타입으로 조회하기보다는, Member와 MemberLike들을 객체들로 가져온 다음 페이지 갯수에 맞게 필터링 해주는 방식으로 했습니다.

다시 보니 private 메서드들에서 pageable들도 함께 넘기면 쿼리 단에서 바로 적용할 수 있었을텐데 지금 방식은 모두 조회하게 한 다음에 자르는 형식이라 메모리 낭비가 더 심할 것이라고 느꼈고, pageable을 내부 메서드로 전달시켜 QueryResults를 통한 전체 사이즈를 이용하도록 수정 완료하였습니다 :)

2024-06-21 07:43 UTC, eom-tae-in commented on src/main/java/com/atwoz/memberlike/domain/MemberLike.java
> +    }
정적 팩토리 메서드에서 findByName으로 검증을 진행하셨군요! 제가 이 부분은 확인을 못했던 것 같습니다 ㅎㅎ

2024-06-21 07:53 UTC, eom-tae-in commented on src/main/java/com/atwoz/memberlike/domain/MemberLike.java
> +    }
매칭이 성사되면 이벤트로 LikeIcon의 상태를 바꾸는 건 좋은 방식인거 같습니다!

2024-06-21 07:53 UTC, eom-tae-in approved these changes

2024-06-21 07:56 UTC, merged