feat: 알림 기능을 적용한다
eom-tae-in/atwoz pull request #41
Opened 2024-07-12 14:57 UTC by devholic22

## 📄 Summary

* FCM 방식을 이용한 알림 시스템을 적용하였습니다. [참고 글](https://headf1rst.github.io/TIL/push-notification)
* 더 빠른 동작을 하기 위해 비동기 방식을 이용하였습니다.
* 다른 도메인에서 알림을 보내고자 할 경우에는 `AlertCreatedEvent`를 발생시키면 됩니다.
    ```java
    public record AlertCreatedEvent(
        AlertGroup group, // 알림 그룹 (좋아요, 알림 등)
        String title, // 알림 제목
        String body, // 알림 상세 내용 (내부 메시지 등)
        String sender, // 발신자의 닉네임
        Long receiverId // 수신자의 ID
    ) {
    }
    ```
* 회원에 대한 FCM 토큰이 필요합니다. 이것을 위해 회원이 로그인할 시 토큰 생성 이벤트 (AlertTokenCreatedEvent)를 발생시키도록 했습니다. (로그인 테스트에 이벤트 발생 검증을 적용하였습니다.)
* 회원이 로그아웃할 시 토큰을 없애야 하는데, 이 경우는 로그아웃 기능이 완료된 뒤 호출하면 될 것 같습니다.
* 회원의 토큰을 관리하는 것으로는 레디스를 이용하였습니다. (갱신/삭제 빈번, 토큰 데이터가 key-value 형식인 점 고려)
* 회원이 받은 알림을 단일 조회할 때는 읽음 여부가 업데이트 됩니다. AlertQueryService와 AlertService 중 어느 곳에 해당 메서드를 둘 지 고민했었는데, AlertQueryService는 순수한 조회, AlertService는 내부 작업이 포함된 모든 기능들을 관리하도록 하는 게 더 나을 것 같아 AlertService에 단일 조회를 두었습니다.
## 🙋🏻 More
* 파이어베이스 빈을 등록할 때 민감한 정보를 드러내지 않기 위해 `@Value`로 암호화된 값들을 가져오고, 이들을 Map으로 만든 뒤 바이트스트림 화 하는 것으로 문제를 해결했습니다. 특히 테스트 환경일 때 문제가 발생했는데, 다행히 파이어베이스에서 기본 GoogleCredentials을 발행해주는 코드가 있어 문제 발생 상황 (IOException, 테스트 환경일 때 발생)을 해결했습니다.
* 알림 보냄 여부를 테스트할 때 Fake 객체로 만들긴 했으나 (FakeAlertManager) 이 방법이 충분할 지 의문이 듭니다. 혹시 더 좋은 방법이 있을지 더 고민해보도록 하겠습니다.

2024-07-12 15:41 UTC, sosow0212 requested changes
수고하셨습니다!
다만 몇가지 질문할 것이 있어서 리뷰 남겼습니다!
해당 부분들 확인해주시고 코멘트 주시면, 확인하고 어프루브 하겠습니다!

2024-07-12 15:41 UTC, sosow0212 commented on build.gradle
> +    implementation 'com.google.firebase:firebase-admin:8.0.0'
혹시 8.0.0으로 하신 이유가 있을까요? 가장 많이 사용하는 버전은 8.1이고 현재는 9버전까지 나와서 어떤 차이가 있는지 몰라서 선택하신 다른 이유가 있는지 궁금해서 여쭤봅니다!

2024-07-12 15:41 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/config/FirebaseConfig.java
> +    private static final String TYPE = "type";
오우 상수화랑 밸류 담느라 고생하셨네요 ㅠ

2024-07-12 15:41 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/domain/Alert.java
> +public class Alert extends SoftDeleteBaseEntity {
이거 softDelete로 처리하신 이유가 있나요?

2024-07-12 15:41 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/infrastructure/AlertQueryRepository.java
> +    public Page<AlertSearchResponse> findMemberAlertsWithPaging(final Long memberId, final Pageable pageable) {
소개팅 어플에선 자주 사용하는 API가 될텐데 인덱싱도 적용해보면 좋을 것 같네요!

2024-07-12 15:41 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/application/AlertService.java
> +    }
스케줄링은 관리를 위해 다른 클래스를 사용하는 건 어떨까요?
- 스케줄 설정도 따로 하지 않아도 될까요? 스케일아웃 환경일 땐 문제가 없을지 궁금하네요!
- 받은 알림은 무조건 자정에 삭제가 되는지도 궁금하네요! 소개팅에서 채팅이 오는 경우도 자정만 되면 삭제될 것 같은데 다른 방법은 없을까요?

2024-07-12 15:41 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/application/AlertEventHandler.java
> +    @EventListener
@TransactionalEventListener와 해당 어노테이션은 무엇이 다를까요!?

2024-07-12 15:41 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/application/AlertService.java
> +        Alert targetAlert = alert.get();
orElseThrow로 축약이 가능해보입니다~

2024-07-12 15:41 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +        firebase.sendAsync(firebaseMessage);
해당 코드가 PR에 적어주신 비동기 처리 부분 같은데 비동기 메서드는 어떻게 작동 될까요?
추가적으로 현재 이벤트가 비동기로 처리돼서 알람을 보냈는데, 서비스부 트랜잭션 커밋 전에 롤백이 발생되면 잘못된 알림이 갈 수도 있을 것 같아요.

제가 잘 모를 수 있어서 이 부분에 대해서 간단하게 코멘트 부탁드립니다!!

2024-07-13 02:03 UTC, eom-tae-in requested changes
고생하셨습니다! 몇가지만 수정 부탁드릴게요~

2024-07-13 02:03 UTC, eom-tae-in commented on src/main/java/com/atwoz/alert/domain/vo/AlertGroup.java
> +    private String name;
final 키워드 붙여주세요~

2024-07-13 02:03 UTC, eom-tae-in commented on src/main/java/com/atwoz/alert/domain/vo/AlertMessage.java
> +    }
이 생성자도 @AllArgsConstructor(access = AccessLevel.PRIVATE)로 하는게 어떨까요?

2024-07-13 02:03 UTC, eom-tae-in commented on src/main/java/com/atwoz/alert/domain/Alert.java
> +    }
이 로직을 @Builder를 추가해서 구현하는 건 어떨까요?

2024-07-13 02:03 UTC, eom-tae-in commented on src/main/java/com/atwoz/alert/domain/AlertManager.java
> +}
AlertManager가 푸시 알람을 보내는 역할을 수행하는거 같은데 이게 도메인에 상태를 바꾸거나 연관이 있나요? 없다면 응용 계층에 두는게 맞을 것 같습니다!

2024-07-13 02:03 UTC, eom-tae-in commented on src/main/java/com/atwoz/alert/domain/Alert.java
> +    private AlertMessage alertMessage;
어노테이션 순서 일치시켜주세요~ :)

2024-07-13 02:03 UTC, eom-tae-in commented on src/main/java/com/atwoz/alert/exception/AlertExceptionHandler.java
> +}
예외 상태 및 메세지를 담당하는 기능 재사용하신거 너무 좋습니다!

2024-07-13 05:37 UTC, devholic22 commented on src/main/java/com/atwoz/alert/domain/vo/AlertMessage.java
> +    }
동의합니다! AllArgsConstructor를 충분히 사용할 수 있었네요. 적용 완료했습니다

2024-07-13 05:37 UTC, devholic22 commented on src/main/java/com/atwoz/alert/domain/Alert.java
> +    private AlertMessage alertMessage;
수정하였습니다!

2024-07-13 05:38 UTC, devholic22 commented on src/main/java/com/atwoz/alert/domain/AlertManager.java
> +}
말씀하신대로 도메인과 관계없는 것 같아 응용 계층으로 수정 완료하였습니다!

2024-07-13 05:39 UTC, devholic22 commented on src/main/java/com/atwoz/alert/domain/Alert.java
> +    }
빌더를 이미 사용할 수 있었네요! 생성자 코드도 제거될 수 있는 만큼 수정 완료했습니다

2024-07-13 05:41 UTC, devholic22 commented on build.gradle
> +    implementation 'com.google.firebase:firebase-admin:8.0.0'
다른 자료들을 봤을 때 처음 접했던 버전이라 적용했었는데, 말씀하신 뒤 파이어베이스의 업데이트 내역을 보니 sendEach, 트래픽 처리 개선 등 더 좋은 기능들이 나온 걸 확인했습니다. 9.3.0 버전으로 변경했습니다 :)

2024-07-13 07:26 UTC, devholic22 commented on src/main/java/com/atwoz/alert/application/AlertEventHandler.java
> +    @EventListener
EventListener는 트랜잭션에 참여하지 않는 환경에서 쓰이고, TransactionalEventListener는 트랜잭션을 인식한 뒤 발생하도록 하는 데 쓰입니다. 
TransactionalEventListener를 이용하면 외부 트랜잭션이 커밋된 후 수행되도록 하는 등의 옵션을 줄 수 있어서, 아래 말씀해주신 상황 (서비스 트랜잭션 롤백)에서의 발생을 방지할 수 있겠다는 생각이 들어 TransactionalEventListener로 수정 완료하였습니다. 
또한 TransactionalEventListener는 커밋이 된 이후 추가 커밋을 허용하지 않는 것을 알게 되어 이를 방지하고자 AlertService에서 REQUIRES_NEW 옵션을 적용하였습니다. (알림 전송은 특정 외부 트랜잭션이 실행되었을 때 발생하는 것으로 생각했습니다.)

2024-07-16 13:19 UTC, eom-tae-in approved these changes

2024-07-18 16:40 UTC, devholic22 commented on src/main/java/com/atwoz/alert/application/AlertService.java
> +    }
* 말씀하신 대로 스케일 아웃 환경일 때에는 스케줄링 메서드를 수행함에 있어 중복 호출될 여지가 있겠다는 생각이 들어, 락 기법 중 레디스의 Redisson을 이용한 분산 락을 이용하였습니다.
* 소개팅에서 채팅이 오는 경우 자정이 되었을 때 삭제시키는 것은 아니고, `모든 알림들 중 생성된 지 60일이 지난 알림들의 상태를 deleted 상태로 업데이트하는 쿼리`라 말씀하신 경우는 해당되지 않는 것 같습니다..!
* 추가로 분산 락을 이용한 테스트 (`RedissonAlertSchedulerTest`)를 작성했는데, 고쳐야 할 게 있다면 다른 방식으로 작성하도록 해보겠습니다.

2024-07-20 10:34 UTC, devholic22 commented on src/main/java/com/atwoz/alert/infrastructure/AlertQueryRepository.java
> +    public Page<AlertSearchResponse> findMemberAlertsWithPaging(final Long memberId, final Pageable pageable) {
Alert를 조회할 때 사용되는 where 쿼리가 모두 동등 쿼리 (`receiver_id = ? and deleted_at is null`)라는 점, order by에 사용되는 정렬 조건이 모두 DESC 내림차순이라는 점을 이용하여 `receiver_id, deleted_at, created_at DESC, id DESC`로 인덱스를 적용하였습니다.

비교를 위해 더미 데이터 백만 건의 데이터를 넣어봤는데, 해당 인덱스를 이용하기 전에는 약 0.548초가 일어났으나 인덱스 적용 후에는 약 0.0025초로 개선할 수 있었습니다.

혹시 인덱스 컬럼 선택을 잘못한 것이라면 피드백 부탁드립니다!

2024-07-22 03:40 UTC, devholic22 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +        firebase.sendAsync(firebaseMessage);
* 이벤트 발행이 기존에 동기적이었다는 점, `@TransactionalEventListener`를 이용할 때 트랜잭션 전파 수준을 REQUIRES_NEW로 하면 심각할 경우 데드락이 발생할 수 있다는 점을 확인하여 이를 해결하기 위해 이벤트 단에 `@Async`를 적용하였습니다. [참고 글](https://seongonion.tistory.com/166?category=929702)
* 비동기 설정 파일 (AsyncConfig)에 비동기 전용 executor, 알림 콜백 전용 executor를 생성했습니다.
* 파이어베이스에서 알림을 호출 (send)할 때, 비동기-논블록킹 방식으로 진행되기 위해 addListener 메서드를 이용하였습니다. [참고 글](https://dd-developer.tistory.com/130) 더불어, 알림 콜백 전용 executor의 스레드 풀 크기는 10개로 설정하였습니다.
* 파이어베이스는 기본적으로 `Executors.newCachedThreadPool()` (요청이 n개면 n개의 스레드를 생성)하는 방식이기 때문에 OOM 이슈가 발생할 수 있다고 판단, 최대 40개의 스레드 제한을 가진 FirebaseThreadManager를 생성하였습니다.
* 알림을 재전송하는 로직을 추가하였습니다. 제한 시간은 파이어베이스에서 권장한 대로 1초, 2초, 4초 세 번을 시도하도록 하였습니다.

정리하자면 알림 비동기 메서드는 다음 과정으로 진행됩니다.
1. 외부 서비스에서 알림 전송 이벤트 (AlertCreatedEvent) 호출
2. 이벤트에 `@Async`가 붙어 있기 때문에 기존 스레드 흐름과 별도로 분리된 스레드 생성됨 - executor로는 비동기 전용 executor
3. 알림 전송 과정에서 별도의 트랜잭션이 필요한 점 + 외부 서비스가 커밋된 이후 이벤트가 발행되어야 한다는 점으로 `@TransactionalEventListener` 적용
4. 파이어베이스 알림 전송 - 파이어베이스의 응답을 비동기적으로 받기 위해 `ApiFuture<String> process`에게 `addListener` 메서드 실행하도록 함 (n번째 파이어베이스 스레드가 n번째 분리된 스레드에게 응답을 담도록 하지 않도록)

2024-07-22 10:50 UTC, sosow0212 requested changes
몇 부분에 대해 질문이 있어서 남겨봤습니다 확인 부탁드립니다!

2024-07-22 10:50 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/config/FirebaseThreadManager.java
> +    private static final int FIREBASE_THREADS_SIZE = 40;
쓰레드 40개로 선정하신 이유가 궁금합니다!

2024-07-22 10:50 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/config/FirebaseThreadManager.java
> +    }
newFixedThreadPool로 쓰레드를 설정해주셨는데요.
만약에 40개의 코어 쓰레드가 모두 사용중이라면 그 이후에 오는 요청은 어떻게 되고 최대 몇 개까지 기다릴 수 있을까요?
그리고 만약 초과가 됐다면 이 경우 대기중인 요청은 어떻게 되나요?

2024-07-22 10:50 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/application/AlertQueryService.java
> +}
이 부분은 페이징을 사용할 때 중복 코드로 발생할 것 같은데
하나의 템플릿을 제네릭으로 만들고 페이징할 때 그걸 extends해서 사용하면 어떨까요?

2024-07-22 10:50 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +    }
AlertManager.send()를 사용하는 부분에서 firebase는 외부 라이브러리일텐데 해당 메서드에서 firebase를 통해 알람을 전송하면 firebase 내부적으로 비동기로 작동이 되나요? (즉, send 메서드에서 firebase에서 알림을 전송할 때 반환을 받든 안 받든 상관없이 기다리지 않냐는 질문입니다!)

2024-07-22 10:50 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +        if (exception.getCause() instanceof FirebaseMessagingException e) {
instanceof는 지양해주세요! [참고](https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/)

2024-07-22 10:50 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +    private void retryInThreeTimes(final Message message) {
많은 양의 알람을 재전송하는데 firebase측의 문제로 쓰레드가 오랫동안 작업을 수행한다면 문제가 생길 수도 있을 것 같은데, redis에 적재해놓고 한 번에 배치처리 하는 것은 어떻다고 생각하시나요?

2024-07-22 10:50 UTC, sosow0212 commented on src/main/java/com/atwoz/alert/infrastructure/RedissonAlertScheduler.java
> +    public void deleteExpiredAlerts() {
네임드락 공통 코드 부분도 AOP로 만들어주시면 재사용하기에 도움될 것 같습니다!

2024-07-28 07:45 UTC, devholic22 commented on src/main/java/com/atwoz/alert/infrastructure/RedissonAlertScheduler.java
> +    public void deleteExpiredAlerts() {
`@RedissonDistributedLock`로 AOP 등록 완료하였습니다!

2024-07-28 07:49 UTC, devholic22 commented on src/main/java/com/atwoz/alert/application/AlertQueryService.java
> +}
좋은 생각입니다! `BaseQueryService` 템플릿을 만들어두었습니다.

2024-07-28 07:51 UTC, devholic22 commented on src/main/java/com/atwoz/alert/config/FirebaseThreadManager.java
> +    private static final int FIREBASE_THREADS_SIZE = 40;
사실 이 부분은 스레드를 얼마까지 정해뒀을 때 수요를 버틸 수 있을지 정확히 예측하기 힘들다고 판단하여 다른 글들을 참고해서 보수적으로 적용했었습니다. 실제 배포 후 모니터링한 뒤 더 늘릴 수 있다면 이후에 늘려보고 싶습니다.

2024-07-28 08:15 UTC, devholic22 commented on src/main/java/com/atwoz/alert/config/FirebaseThreadManager.java
> +    }
* 우선 알림을 보낼 때 영향이 끼쳐지는 스레드는 FirebaseThreadManager에서 관리하는 스레드가 아닌, AsyncConfig에서 관리하는 스레드입니다. (AsyncConfig의 getAsyncExecutor 메서드)
* 지정한 `MAX_THREAD_SIZE + QUEUE_SIZE`개 만큼의 수요 (지금은 MAX_THREAD_SIZE 40, QUEUE_SIZE 100이므로 140개 가능)를 감당한 뒤 나머지 처리에 대해서는 ThreadPoolExecutor에서 전략을 설정할 수 있는데, 우선은 이벤트를 호출한 스레드 (즉, 스프링 메인 스레드)에서 나머지를 보내도록 설정하였습니다. (ThreadPoolExecutor.CallerRunsPolicy 전략)
  * `AbortPolicy`: TaskRejectedException이 발생되고 요청이 무시됩니다.
  * `CallerRunsPolicy`: 처리되지 못한 요청을 ThreadPool을 호출한 Thread에서 처리합니다.
  * `DiscardPolicy`: 처리되지 못한 요청을 무시합니다.
  * `DiscardOldestPolicy`: 가장 오래된 요청을 삭제하고 다시 execute를 실행합니다.
  * 이에 따라, 알림을 보내야 하는 상황에서 무시하거나 예외를 발생시키기보다는 메인 스레드를 이용해서라도 진행시켜야 하는 게 맞겠다는 생각이 들어 CallerRunsPolicy를 선택하였습니다.
* 그럼에도 FirebaseThreadManager에서 스레드를 따로 지정한 이유는 기본적으로 파이어베이스가 요청이 n개 들어온다면 n개만큼의 스레드를 만들기 때문에, 극단적인 예로 10,000개의 알림을 보내야 한다면 10,000개의 스레드를 만들게 되고 이로 인해 OutOfMemory 현상이 발생할 수 있음을 확인하였어서 지정했었습니다.

2024-07-28 10:52 UTC, devholic22 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +    }
* firebase의 sendAsync 메서드를 이용하면 파이어베이스 내부적으로도 비동기적으로 작동되고, ApiFuture (Future의 자식 객체)를 반환합니다.
* 이때 ApiFuture.get 메서드를 이용하면 응답 값을 받을 수 있으나, get 메서드를 이용하는 순간 동기적으로 작동하기 때문에 get을 통한 방식보다는 addListener 방식을 이용하여 콜백 메서드로 실행되게끔 하였습니다. (비동기-논블록킹)

![스크린샷 2024-07-28 오후 7 46 41](https://github.com/user-attachments/assets/eacd3745-8f0e-4584-906e-39a83cb0e4b7)
예시로 첫 번째 경우는 `firebase.sendAsync(firebaseMessage).get()` 방식 (동기)으로 바로 이끌어낸 경우이며, 이 때는 알림 작업을 진행한 스레드가 알림 작업의 결과까지 받아옵니다.

![스크린샷 2024-07-28 오후 7 51 36](https://github.com/user-attachments/assets/ed0cc336-ad73-47fc-a592-be77f06d506d)
그러나 두 번째 경우 (현재 코드, Runnable 및 addListener 방식)는 알림 작업을 진행한 스레드가 결과를 받는 게 아니라, 스레드 풀에 남아있는 다른 스레드가 알림 작업의 결과를 받아오게 됩니다.

2024-07-29 07:14 UTC, devholic22 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +        if (exception.getCause() instanceof FirebaseMessagingException e) {
instanceof 대신 ClassCastException을 try-catch 하는 식으로 리팩터링 하였습니다.

2024-07-29 07:18 UTC, devholic22 commented on src/main/java/com/atwoz/alert/infrastructure/FirebaseAlertManager.java
> +    private void retryInThreeTimes(final Message message) {
파이어베이스 알림 전송 과정에서 재전송을 해야 하는 경우가 빈번히 발생하지는 않을 것 같아 지금은 배치 처리를 하지 않았는데, 지금 단계에서 배치 작업을 진행해야 할 지 고민이 듭니다. 모니터링 과정을 거친 뒤에 실제 알림이 빈번히 재전송을 해야 할 필요성이 느껴질 때 반영해도 괜찮을까요?

2024-07-29 07:36 UTC, sosow0212 approved these changes

2024-07-29 08:18 UTC, merged