feat: OAuth2 로그인 구현
eom-tae-in/atwoz pull request #5
Opened 2024-01-23 10:37 UTC by eom-tae-in

OAuth2 기반 설정 작업을 하였습니다.

## 📄 Summary

  카카오 환경에서의 OAuth2 로그인 처리를 하였습니다.

## 🙋🏻 More

 - 기존 등록되어있던 signup 엔드포인트를 삭제하고, login만 남겨두었습니다. 이제 유저는 처음에 회원가입 되어있지 않았을 경우 생성, 기존에 있을 경우 해당 유저를 반환합니다.
 - `login/{provider}`로 POST 요청을 보내는데, provider는 kakao, naver 등의 OAuth2 회사 이름을 의미합니다.

close #4

2024-02-04 07:41 UTC, sosow0212 requested changes
approve 하기 전에 몇 가지가 궁금해서 rc 누릅니다! 수고하셨습니다~

2024-02-04 07:41 UTC, sosow0212 commented on src/main/java/com/atwoz/global/config/CustomRequestWrapper.java
> +public class CustomRequestWrapper extends HttpServletRequestWrapper {
이건 뭘 하는 클래스인가요??

2024-02-04 07:41 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/auth/AuthService.java
> +    public String login(final LoginRequest request, final OAuthProvider provider) {
참조 관계 끊고 아주 좋습니다 굿

2024-02-04 07:41 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/auth/OAuthRequester.java
> +
불필요한 공백 삭제해주세요

2024-02-04 07:41 UTC, sosow0212 commented on src/main/java/com/atwoz/member/infrastructure/auth/JackonJsonMapper.java
> +public class JackonJsonMapper implements JsonMapper {
이거 잭슨 말고 resttemplate에서 할 수 없을까요?

2024-02-04 07:41 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/member/MemberServiceTest.java
> +        Member member = memberRepository.findByEmail(email).get();
이렇게 테스트하기 보다는
softly로 생성이 됐는지 `optinal.isPresent()`로 먼저 검증하고 그다음 ast를 검증하는게 좋지 않을까요?

2024-02-08 18:02 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/infrastructure/auth/JackonJsonMapper.java
> +public class JackonJsonMapper implements JsonMapper {
restTemplate로 통신을 담당하는 클래스를 만들었는데 그 안에 JSON을 매핑하는 라이브러리까지 존재하면 나중에 JSON을 변환해주는 라이브러리가 바뀔 경우 유지보수에 불편함이 있을 것 같아서 분리했습니다. 또한 JSON을 매핑하는 라이브러리를 다른 클래스에서도 사용하기 때문에 클래스를 따로 분리하여 관리하는 것이 이점이 더 있다고 생각했습니다:)

2024-02-08 18:03 UTC, eom-tae-in commented on src/test/java/com/atwoz/member/application/member/MemberServiceTest.java
> +        Member member = memberRepository.findByEmail(email).get();
그렇네요!
좋은 방법 공유해주셔서 감사합니다~

2024-02-09 02:59 UTC, sosow0212 approved these changes
계층 분리랑 다른 부분도 너무 잘해서 approve 하겠습니다!
리뷰 남긴 몇 부분만 수정하고 머지해주세요!

2024-02-09 02:59 UTC, sosow0212 commented on src/main/java/com/atwoz/member/infrastructure/auth/JwtTokenProvider.java
>  @Getter
Getter는 필요없어 보입니다!

2024-02-09 02:59 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/auth/support/auth/OAuthPlatform.java
> +                .orElseThrow(IllegalArgumentException::new);
이거 정확히 어떤 오류인지 파악하기 위해서 CustomException으로 바꾸는 게 좋아보입니다

2024-02-10 03:41 UTC, devholic22 requested changes
수고하셨습니다! 자잘한 몇 개만 수정해주시면 될 거 같습니다 :)

2024-02-10 03:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/auth/support/auth/RequestProcessor.java
> +}
사용 위치가 0곳으로 나오는데 다른 곳에서 대신 처리하신 것 같습니다! 없애도 괜찮을까요?

2024-02-10 03:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/auth/JsonMapper.java
> +}
final 속성 붙여주시면 좋을 것 같습니다!

2024-02-10 03:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/auth/JackonJsonMapper.java
> +                .reduce(jsonNode, JsonNode::get, (a, b) -> b)
혹시 a, b 말고 다른 이름으로 바꿔주실 수 있을까요?

2024-02-10 03:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/auth/dto/OAuthProviderRequest.java
> +) {
지금으로선 굳이 필요하지 않을 수도 있을 것 같긴 한데, 만약 OAuthProvider 회사들에서 제공하는 이름 형식이 달라지거나 위의 값이 없다면 (ex: clientSecret) 해당 OAuthProvider 방식은 지원이 안된다는 메시지를 전달해야 할 수도 있을 것 같습니다. 컨트롤러에 요청 시 넘어오는 정보인만큼 LoginRequest와 같이 `@Valid` 및 예외처리를 해 주면 어떨까요? (MemberInfoKeyWordRequest도 동일)

2024-02-10 03:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/auth/JwtTokenProvider.java
>          Claims claims = Jwts.claims();
파라미터로 넘겨온 인자를 이용해 Claims를 만들고 그것을 이용해 토큰을 만든 뒤 반환하는 것인데, `createTokenWith`와 비슷하게 어떤 것을 이용해 토큰을 만든다는 느낌이 들게 메서드명을 정해주면 좋을 것 같습니다!

2024-02-10 03:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/auth/RestTemplateOAuthConnection.java
> +
params.add에 쓰인 키 (grant_type, client_id 등)들을 상수처리하지 않은 이유가 있으실까요?
아니면 params에 여러 키를 저장하니, 메서드로 분리해주시면 좋을 것 같습니다.

2024-02-10 03:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/auth/OAuthRequester.java
> +
공백 지워주시면 좋을 것 같습니다 :)

2024-02-10 03:44 UTC, devholic22 approved these changes

2024-02-10 07:37 UTC, merged