refactor: member 바운디드 컨텍스트에서 job, hobby, profile, selfintro를 분리한다
eom-tae-in/atwoz pull request #78
Opened 2024-10-08 08:40 UTC by eom-tae-in

## 📄 Summary

- member에 속해 있던 job, hobby, profile, selfintro를 모두 분리하였습니다.
- job은 api를 통해 상태가 관리되도록 변경했습니다.

## 🙋🏻 More

수정 범위가 너무 넓어서 제가 작업한 부분 이외에 실패하는 테스트는 주석 처리를 했습니다. 전반적인 수정사항을 참고하셔서 수정하시면 될 것 같습니다!

2024-10-11 16:56 UTC, devholic22 requested changes
너무 수고하셨습니다!

파일이 많다 보니 코멘트도 살짝 많은 것 같습니다 🙇

추가로 쿼리에 대한 부분이 꽤 쿼리 최적화가 많이 필요하겠다는 생각이 들었습니다. 특히 ProfileQueryRepository와 BooleanBuilder가 있던 리포지터리 부분이 그런 것 같아요

지금 생각으로는 빠른 개발을 먼저 하고 이후에 리팩터링을 하는 게 더 좋을 것 같습니다

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/application/dto/JobCreateRequest.java
>          @NotBlank(message = "스타일 이름을 입력해주세요.")
레코드가 Style에서 Job으로 바뀌었으나 필드 설명은 계속 스타일로 되어 있는 것 같습니다

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/application/dto/JobUpdateRequest.java
>          @NotBlank(message = "스타일 이름을 입력해주세요.")
Style -> Job에 대한 설명으로 수정해야 할 것 같습니다!

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/exception/JobExceptionHandler.java
> +        return getErrorMessageWithStatus(e, HttpStatus.CONFLICT);
중복 에러 차원에서 conflict를 선택한 게 더 좋아보입니다! 그런데 혹시 이렇게 존재 유무에 대한 예외를 다른 곳들에 많이 작성했었을텐데 그 부분들에서는 bad request로 했던 것으로 기억합니다. 이 부분은 향후 bad request들을 모두 지금처럼 conflict로 바꾸는 작업이 필요할 것 같습니다 :)

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/exception/exceptions/JobNameAlreadyExistedException.java
> +        super("이미 존재하는 스타일 이름입니다");
직업에 관한 것으로 하는 게 더 맞아보입니다

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/exception/exceptions/JobCodeAlreadyExistedException.java
> +        super("이미 존재하는 스타일 코드입니다.");
직업으로 변경 부탁드립니다 :)

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/exception/exceptions/InvalidJobException.java
> +        super("등록되지 않은 스타일입니다.");
직업에 대한 내용으로 두는 게 맞을 것 같습니다!

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/member/MemberPushNotifications.java
> +                false,
내부에 필드들이 많으니 여기에도 빌더를 써 보는 건 어떨까요?

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/member/dto/MemberNotificationsResponse.java
> +
공백이 별도로 필요하진 않아도 될 것 같습니다 :)

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/profile/domain/Profile.java
> +    // memberId로 member 간접 참조
memberId와 jobCode는 필드만으로 충분히 간접 참조가 이해되어서, 주석이 없어도 될 것 같습니다

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/ui/JobController.java
> +    public ResponseEntity<Void> updateJob(@PathVariable("jobId") final Long jobId,
저희 논의한 것 처럼, 컨트롤러에서 인자가 두 개 이상이면 줄바꿈 쳐서 진행하는 것으로 적용해주시면 될 것 같습니다 :)

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/member/dto/MemberAccountStatusPatchRequest.java
> +
불필요한 공백 같습니다

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/member/dto/MemberContactInfoPatchRequest.java
> +
불필요한 공백 같습니다

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/profile/ui/ProfileController.java
> +            @ModelAttribute final ProfileFilterRequest request
ProfileFilterRequest들을 ModelAttribute로 한 이유는 생성 과정에서 cities를 변환하는 과정이 있기 때문인 것일까요?

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/hobby/application/HobbyEventHandler.java
> +    public void savePopupsTags(final ProfileFetchStartedEvent event) {
메서드 이름에 대해 더 설명해주실 수 있으실까요?

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/application/JobService.java
> +@Transactional
Required / Transactional / Service 순서로 부탁드립니다 :)

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/job/application/dto/JobPagingResponses.java
> +    private static final int NEXT_PAGE = 1;
NEXT_PAGE, NO_MORE_PAGE를 들고 있지 않아도 될 것 같습니다

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/profile/application/ProfileService.java
> +                memberId,
Profile.createWith와 update 이용에 대해 더 논의해보면 좋을 것 같습니다. 필드가 너무 많다 보니 뭔가 더 수정하면 좋을 것 같은데 고민이네요..!

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/profile/application/dto/ProfileCreateRequest.java
> +
불필요한 공백 있습니다.

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/profile/domain/UserHobbies.java
> +public class UserHobbies {
Member에서 User로 수정하신 이유가 있나요?

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/profile/domain/UserHobbies.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
NoArgs가 이전에 쓰던 protected에서 public으로 되었는데 의도하신 것인지 궁금합니다.

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/member/Member.java
> +    // TODO: 회원 가입 및 로그인 진행 시 해당 메서드를 추가하여 최근 방문일을 갱싱해줘야 한다.
주석 오타있습니다 :)

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/profile/infrastructure/ProfileQueryRepository.java
> +    // TODO: 우선 가장 인기 있는 회원 한 명만 조회되도록 설정함. 추후에 이야기 해서 상위 5%를 어떻게 설정할지 논의해봐야함.(쿼리 최적화도)
ProfileQueryRepository가 진짜 조회가 어마어마 하네요.. 꼭 논의해봐야 할 듯 합니다!

2024-10-11 16:56 UTC, devholic22 commented on src/main/java/com/atwoz/selfintro/infrastructure/SelfIntroQueryRepository.java
> +
불필요한 공백 있습니다

2024-10-12 00:35 UTC, eom-tae-in commented on src/main/java/com/atwoz/job/exception/JobExceptionHandler.java
> +        return getErrorMessageWithStatus(e, HttpStatus.CONFLICT);
네 이 부분은 예외처리 리팩터링 진행하실 때 추가해주시면 감사하겠습니다 :)

2024-10-12 00:39 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/member/MemberPushNotifications.java
> +                false,
빌더를 적용하는게 더 좋아보이네요! 추가하겠습니다

2024-10-12 00:45 UTC, eom-tae-in commented on src/main/java/com/atwoz/profile/ui/ProfileController.java
> +            @ModelAttribute final ProfileFilterRequest request
@ModelAttribute를 사용한 이유는 get요청에서 받아야하는 값들이 많기 때문입니다. 필터 조건들을 모두 @RequestParam으로 받으면 컨트롤러 매개변수가 너무 많아지게 되고 중복되는 코드 줄이 많이 생기게 됩니다. 또한 @ReqeustParam은 컨트롤러에서 받은 후 따로 검증을 진행해야합니다. 이런 조건들을 생각해봤을 때 @ModelAttribute를 사용하는 것이 더 적합하다고 생각했습니다.

2024-10-12 00:48 UTC, eom-tae-in commented on src/main/java/com/atwoz/hobby/application/HobbyEventHandler.java
> +    public void savePopupsTags(final ProfileFetchStartedEvent event) {
다른 프로젝트를 병행해서 진행하다가 실수로 네이밍을 잘못 정한 것 같습니다 ㅠㅠ
`checkHobbyExists`로 네이밍을 수정하였습니다.

2024-10-12 00:50 UTC, eom-tae-in commented on src/main/java/com/atwoz/profile/application/ProfileService.java
> +                memberId,
흠 이 부분처럼 개선이 필요한 부분을 회의 일정을 잡아서 문서화를 진행하면 좋을 것 같네요

2024-10-12 00:54 UTC, eom-tae-in commented on src/main/java/com/atwoz/profile/domain/UserHobbies.java
> +public class UserHobbies {
이 부분은 회원 바운디드 컨텍스트의 루트 애그리거트(Member) 이름과 겹치는 것이 혼란을 줄 수도 있겠다는 생각에 Member가 아닌 User를 사용하였습니다. 다른 바운디드 컨텍스트에서도 이런 경우에 대해 다른 이름으로 지정하는 것이 어떨까요?

2024-10-12 00:55 UTC, eom-tae-in commented on src/main/java/com/atwoz/profile/domain/UserHobbies.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
이 부분은 제가 인지를 못했던 거 같네요... 수정하겠습니다!

2024-10-12 00:57 UTC, eom-tae-in commented on src/main/java/com/atwoz/profile/infrastructure/ProfileQueryRepository.java
> +    // TODO: 우선 가장 인기 있는 회원 한 명만 조회되도록 설정함. 추후에 이야기 해서 상위 5%를 어떻게 설정할지 논의해봐야함.(쿼리 최적화도)
네 회의 일정 맞춰서 한번 논의해보면 좋을 거 같아요!

2024-10-12 02:18 UTC, devholic22 commented on src/main/java/com/atwoz/profile/ui/ProfileController.java
> +            @ModelAttribute final ProfileFilterRequest request
ModelAttribute를 쓰게 된 이유를 공유해주셔서 감사합니다!

2024-10-12 02:19 UTC, devholic22 commented on src/main/java/com/atwoz/profile/domain/UserHobbies.java
> +public class UserHobbies {
이게 말씀하신 바운디드 컨텍스트에 해당되는 것이군요! 좋은 생각인 것 같습니다.

2024-10-12 02:20 UTC, devholic22 approved these changes
수고하셨습니다!

2024-10-12 02:47 UTC, merged