feat: 회원 상세 정보 저장 및 조회 구현
eom-tae-in/atwoz pull request #9
Opened 2024-02-13 08:34 UTC by devholic22

## 📄 Summary
- [x] 회원가입 시 필요한 회원 정보 속성 정의
- [ ] 회원 정보 저장
- [ ] 회원 정보 조회
- [ ] 회원 정보 수정 & 삭제
- [ ] 연애 모의고사 데이터 저장
- [ ] 연애 모의고사 답변 저장
- [ ] 연애 모의고사 답변 수정

## 🙋🏻 More
### 회원 정보 속성
* 회원 (Member)에는 가급적 테이블에서 회원가입 시 작성한 정보 (취미 등)를 직접 필드로 가지지 않도록, 테이블을 별도로 만들어 회원의 id를 참조하는 식으로 작성하였습니다.
* List 형태로 관리할 Hobbies, Styles 등에 대해서는 일급 컬렉션으로 만든 뒤, `@ElementCollection`과 `@Embeddable`을 이용해 Member와 연결되도록 하였습니다. 그래서 Member.java에 작성되어 있어도 데이터베이스 상으로는 분리되어 있습니다.
* Location (위치) 관련해서는 우선은 기획안대로 city (시/도), sector (구)로 저장되도록 했습니다.
>

#7

2024-02-23 09:54 UTC, sosow0212 requested changes
File Changed가 100개가 넘어서 리뷰하는데 너무 힘들었습니다 ㅠ
다음부터는 작업이 길어질 것 같으면 pr을 나눠서 제출하는게 더 좋을 것 같습니다!
불필요하게 나눈 부분도 있는 것 같고 설계하신 부분 중에 몇 가지가 궁금해서 코멘트 남겼습니다!

2024-02-23 09:54 UTC, sosow0212 commented on src/docs/asciidoc/option.adoc
> +==== 요청
요청에는 문서가 없네요 어떤 url로 어떤 요청을 하는지 모를 것 같은데
필드가 없다면 http-request.adoc[] 을 사용하는게 좋아보이네요 다른 부분에도 마찬가지지만 요청, 응답 두 부분에 http는 모두 붙여주세요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +        OptionWriteRequest optionWriteRequest = request.option();
사소한거긴한데 이건 큰 로직이 없는 부분인데, 변수로 추출하지 말고 이벤트에 보낼 때 매개변수로 request.profile로 태우는 건 어떨까요?

변수 추출한다면 밑에 stream을 사용하는 부분에서 오히려 변수로 추출하는 게 더 나아보여서요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +                .toList();
이 부분도 각각 메서드 분리 한 번씩 해주면 좋을 것 같아요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/HobbyWriteRequest.java
> +
매개변수 안에 있어서 한 칸 띄우지 않아도 됩니다!

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/InfoWriteRequest.java
> +
1. 공백을 넣은 이유가 뭘까요?
2. validation을 생략하신건가요?

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/hobby/HobbyService.java
> +        deleteMemberHobbies(memberId);
프론트에서 중복으로 해당 메서드를 재사용할 것 같지 않아서 지우는 행위는 업데이트하는 메서드에서 해줘도 될 것 같습니다.

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/hobby/HobbyService.java
> +    public void deleteMemberHobbies(final Long memberId) {
saveMemberHobbies에서만 사용하는데 접근제어자가 public으로 되어있습니다.
그리고 지금은 메서드로 나눌 필요가 없어보이네요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/option/OptionFactory.java
> +
불필요한 공백있습니다

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/option/OptionFactory.java
> +@Component
1. 해당 클래스는 무엇을 하는 클래스인가요?
2. Component를 통해 빈으로 등록하신 이유가 무엇인가요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/option/OptionService.java
> +    public void writeOption(final Long memberId, final OptionWriteRequest request) {
write인데 업데이트까지 같이 해주는 것 같네요 나누는 것이 낫지 않을까요?

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/option/OptionService.java
> +    private boolean isMemberOptionExist(final Long memberId) {
이것도 단일 repository 메서드인데 메서드로 분리할 필요가 없어보입니다

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/profile/ProfileFactory.java
> +    }
이 부분을 메서드로 나눈 이유가 무엇인가요? `return new Body(~)` 이 부분은 메서드로 나뉘어 있지 않네요.
일관성이 없고, 불필요하게 나눠서 너무 많은 메서드로 가독성이 오히려 떨어지는 것 같습니다

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/profile/ProfileService.java
> +    private final ProfileFactory profileFactory;
Factory가 필요한지 의문이 드네요.
생성의 책임을 나누는 클래스인 것 같은데 그 역할에 로직이 있는 것도 아니고 빈으로 등록해서 주입 받아 사용하는 것은 크게 의미가 없어보입니다.
 그냥 해당 클래스에서 만드는 메서드를 만들거나 해도 되지 않을까요?

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/config/AuthConfig.java
> +                .addPathPatterns("/**", ANY);
`/**`로 설정하면 모든 url에 대해 인터셉터를 할텐데 이렇게 하신 이유가 무엇인가요?

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/auth/TokenProvider.java
> +    String extract(final String token);
* re
이거 rebase하면서 바뀐 것인가요? 아니면 직접 바꾸신건가요?

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/auth/interceptor/LoginValidCheckerInterceptor.java
> +                .orElseThrow(RuntimeException::new);
이 부분도 필요하나요? 조회를 최소화 하려고 id를 준 것인데 무조건 조회가 발생하는 것 같네요
토큰에서 email을 찾고 그걸로 member를 조회하고 id를 심는게 아무런 의미도 없어보여요
토큰에서 id값이 담겨있다면 그걸로 이미 가입된 멤버임을 알 수 있지 않나요?

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    GAME("PC · 모바일 게임"),
`·` 기호를 저렇게 valaue로 하신 이유가 있을까요? 프론트에서 따로 코드로 전달된다고 그랬는데 아무런 의미가 없어보입니다 ㅠ

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    }
1.  외부에서 사용하지 않습니다 접근제어자 수정해주세요
2. validateEmptySizeOfHobbies
3. validateDuplicatedHobbies
4. validateOverMaxSizeOfHobby

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyRepository.java
> +    List<Hobby> findAllByMemberId(Long memberId);
매개변수에 여기는 final이 없네요 모두 없어도 되는데 통일해주세요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/info/option/Option.java
> +    public Option(final Long memberId, final Smoke smoke, final Religion religion,
매개변수를 3개씩 나눈 이유가 무엇인가요?? 개행을 하나씩 넣어주는게 나아보여요 저런 컨벤션은 없었습니다 ㅠ

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/info/profile/Body.java
> +            throw new ProfileRangeException();
예외 메시지가 너무 단순합니다. 구체적으로 다른 Exception을 사용하는게 좋을 것 같습니다
그리고 테스트 코드에서도 합쳐서 사용중인데 분리해서 작성해주세요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/info/profile/Position.java
> +    private double latitude;
위도 경도면 BigDecimal로 바꾸는 건 어떨까요? double과 무슨 차이가 있을까요?

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/domain/info/profile/year/YearManager.java
> +public interface YearManager {
현재 플로우는
1. factory에서 사용중이고
2. 외부 서비스에서 getCurrentYear로 생성하고
3. 도메인을 생성할 때 이 값을 넘겨주며 생성하고
4. 생성시 나이를 계산

이런 구조로 되어있는데, 도메인 서비스로 도메인 생성자나 다른 부분에 넘겨서 한 번에 해주도록 하는게 나아보입니다
외부에 노출될 필요가 없을 것 같아서요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/infrastructure/info/option/OptionRepositoryImpl.java
> +    }
이렇게 만든 이유가 있을까요?
jdbc를 사용하든, jpa에서 다른 메서드를 사용해서 더 효율적으로 쿼리를 날릴 수 있습니다 ex. count query...

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/info/HobbyController.java
> +public class HobbyController {
info부분에서 다 해결될 것 같은데 따로 hobby, option 등등을 컨트롤러랑 서비스를 나눈 이유를 잘 모르겠습니다. 
그리고 Restful 계층 구조도 안지켜지고 있는 것 같습니다.

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/info/InfoController.java
> +
불필요한 공백이 있습니다

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/info/InfoController.java
> +        return ResponseEntity.ok()
생성은 201 응답 주기로 한 것 같습니다!

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/info/StyleController.java
> +                .map(styleName -> new StyleSearchResponse(styleName.getName()))
이것도 한 번에 변경할 수 있을 것 같네요

2024-02-23 09:54 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/info/StyleController.java
> +    public ResponseEntity<List<StyleSearchResponse>> findMemberStyles(@AuthMember Long memberId) {
여기 매개변수에는 final이 생략되어 있습니다

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/HobbyServiceTest.java
> +public class HobbyServiceTest {
테스트 클래스는 public 접근 제어자 붙일 필요가 없습니다.

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/HobbyServiceTest.java
> +@ExtendWith(MockitoExtension.class)
Mockito를 사용하는 이유가 무엇인가요? 이미 Fake로 테스트하는 것 같습니다

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +    ApplicationEvents events;
접근 제어자가 없습니다

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +@ExtendWith(MockitoExtension.class)
해당 어노테이션들을 각각 붙인 이유가 궁금합니다!

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +        );
지금처럼 정보가 많다면 Fixture를 사용하는게 다른 계층에서 사용할 때에도 테스트 로직에 더욱 가독성있게 볼 수 있어서 좋을 것 같습니다.

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +        assertSoftly(softly -> {
정보가 저장되었는지 확인은 안해도 되나요?

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/OptionServiceTest.java
> +@ExtendWith(MockitoExtension.class)
여기도 mockito를 사용한 이유가 무엇인가요?

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/ProfileServiceTest.java
> +            softly.assertThat(profileRepository.findByMemberId(memberId)).isPresent();
이 두 개는 겹치는 거 같네요

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/ProfileServiceTest.java
> +            softly.assertThat(profileRepository.findByMemberId(memberId).get()).isEqualTo(expectedProfile);
equals를 id로 재정의 했다면 id 값만 같으면 true를 반환할텐데 값도 같이 검증하는게 중요할 것 같습니다. 다른 메서드를 통해서 검증해보면 좋을 것 같습니다

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/fixture/info/BodyFixture.java
> +    private static final int HEIGHT = 171;
fixture에서 다른 클래스에선 변수로 바로 할당해주거나 하는데 이 부분에서만 상수화한 이유가 있을까요?

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/infrastructure/info/HobbyFakeRepository.java
> +        map.put(id, newHobby);
이렇게 되면 저장된 newHobby에서는 id 값이 null일 것 같아요

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/ui/info/HobbyControllerWebMvcTest.java
> +    private OAuthArgumentResolver oAuthArgumentResolver;
test / helper 패키지에 가면 MockBeanInjection 클래스가 있습니다 여기에 MockBean을 모두 넣고 상속받아 사용하면 캐싱돼서 빨라집니다 `@MockBean(JpaMetamodelMappingContext.class)`도 해당 클래스에 같이 넣어주세요

2024-02-23 09:54 UTC, sosow0212 commented on src/test/java/com/atwoz/member/ui/info/HobbyControllerWebMvcTest.java
> +        when(authArgumentResolver.resolveArgument(any(), any(), any(), any())).thenReturn(memberId);
요청 보낼 때 헤더값에 토큰을 넣으면 이런 부분 모두 필요 없습니다 어차피 문서화하려면 헤더에 토큰을 넣는 것까지 테스트 해야하는데 바꿔야할 것 같습니다

2024-02-23 10:14 UTC, eom-tae-in requested changes
리뷰했습니다. 내용 반영해서 수정해주세요.
+ 왜 인수테스트는 작성하지 않으신건가요?? 
+ 조금만 신경써도 수정할 수 있는 내용이 많았습니다. 다음부터는 이런 부분 신경써서 해주세요

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/info/hobby/Hobby.java
> +public class Hobby {
지금 enum 타입으로 관리하는 클래스의 이름을 Hobby로 변경하고 해당 클래스의 이름을 MemberHobby로 변경하는 것이 좀 더 클래스를 파악하기 쉬울 것 같습니다.

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    }
size에 대한 검증을 메서드로 분리하신 거 같은데 이 메서드도 분리하는 게 좀 더 좋아보입니다.
1. names가 비었는지 검증하는 메서드
2. names의 중복을 검증하는 메서드
3. names의 크기가 최대 size를 넘는지 검증하는 메서드
이렇게 분리를 한 번더 하면 어떨까요?

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    }
정적 팩토리 메서드라 네이밍 컨벤션을 따라 매개변수가 1개라 from이라는 네이밍을 주신 것 같습니다. 
하지만 이 메서드의 이름인 from으로 해당 메서드의 기능을 파악할 수 있을까요?
제가 보기엔 이런 상황에서는 좀 더 주체적인 네이밍을 부여하는게 더 좋아보입니다!
저라면 메서드의 이름을 findBy로 하여 Hobbyname.findBy(String.class); 이런식으로 메서드를 호출하도록 할 것 같습니다:)

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyRepository.java
> +    List<Hobby> findAllByMemberId(Long memberId);
final 키워드 추가해주세요

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/info/image/Images.java
> +    @ElementCollection
값타입 컬렉션은 값을 변경했을 때 기존의 값을 모두 delete하고 다시 insert하는 단점이 있습니다. 다른 방법을 고민해보는 것이 좋을 것 같습니다.

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/info/profile/Body.java
> +    }
Math.abs()로 currentYear - birthYear를 하신 이유가 뭔가요? (currentYear가 birthYear보다 작을 수가 있나요?)
만약 임의로 birthYear를 선택할 수 있어서 birthYear로 currentYear보다 큰 값을 선택할 수 있다면 이건 따로 예외처리를 해야할 것 같은데 어떻게 생각하시나요?

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/infrastructure/info/hobby/HobbyJpaRepository.java
> +    List<Hobby> findAllByMemberId(Long memberId);
final 키워드 추가해주세요

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/ui/info/OptionController.java
> +    public ResponseEntity<OptionSearchResponse> findOption(@AuthMember Long memberId) {
final 붙여주세요

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/ui/info/StyleController.java
> +                .toList();
컨트롤러에서 직접 변환해주지 말고 dto에서 해주는게 좋아보입니다

2024-02-23 10:14 UTC, eom-tae-in commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +@SpringBootTest
통합 테스트를 할 때 RANDOM PORT 설정을 하는 이유가 뭘까요? 찾아보시고,
이 테스트는 서비스 테스트인데 왜 @SpringBootTest를 하는 걸까요?

2024-02-23 10:14 UTC, eom-tae-in commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +    }
이걸 여기다가 왜 붙였나요?

2024-02-23 10:14 UTC, eom-tae-in commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +
given 절의 설정이 너무 긴 것 같습니다. 불필요한 공백도 제거해주세요~

2024-02-23 10:14 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/domain/info/profile/year/YearManagerImpl.java
> +
계층 구조상 현재 추상화한 인터페이스 클래스와 같은 도메인 위치에 있는데 이게 과연 올바른 계층 구조일까요?

2024-02-23 11:03 UTC, devholic22 commented on src/docs/asciidoc/option.adoc
> +==== 요청
수정 완료하였습니다!

2024-02-23 11:09 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/dto/HobbyWriteRequest.java
> +
수정 완료하였습니다!

2024-02-23 11:20 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    }
1. 수정했습니다. 메서드명을 `validateNames`로 변경했습니다.
2. `validateIsNotEmptyNames`로 변경하였습니다.
3. `validateIsUniqueNames`로 변경하였습니다.
4. `validateIsNotOverMaxSizeOfHobby`로 변경하였습니다.

2024-02-23 11:22 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyRepository.java
> +    List<Hobby> findAllByMemberId(Long memberId);
수정 완료했습니다!

2024-02-23 11:35 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/option/OptionFactory.java
> +
수정했습니다!

2024-02-23 11:39 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    }
네 각각 validateIsNotEmptyNames, validateIsUniqueNames, validateIsNotOverMaxSizeOfHobby로 분할하였습니다!
검증 로직이 여러 개일 경우 나누는 습관을 들여왔었는데 이 부분에서 작성하지 않았었네요
다음부터는 습관을 다시 지키도록 하겠습니다

2024-02-23 11:39 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyRepository.java
> +    List<Hobby> findAllByMemberId(Long memberId);
수정하였습니다!

2024-02-23 11:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/info/hobby/HobbyJpaRepository.java
> +    List<Hobby> findAllByMemberId(Long memberId);
수정하였습니다!

2024-02-23 11:44 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/OptionController.java
> +    public ResponseEntity<OptionSearchResponse> findOption(@AuthMember Long memberId) {
수정하였습니다! 추가로 다른 컨트롤러들에서도 `final`이 붙여져있지 않음을 알게 되었습니다.. 이러한 부분이 말씀하신 `조금만 신경써도 수정할 수 있는 내용`인 것 같습니다. 기본적인 것을 많이 못 지켰는데, 이야기 해 주셨듯 다음 작업들에서는 제출 전 파일들을 점검해보는 시간을 더 길게 가지겠습니다.

2024-02-23 11:49 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/profile/Body.java
> +    }
실제로는 currentYear는 시스템을 이용해서 현재 연도를 가져올 것이고, 프론트에서는 최대 연도를 지정할 것이기에 이러한 경우는 존재하지 않아 `Math.abs`를 없애는 식으로 해도 될 것 같습니다.

이후에는 `유저 입장에서 작성 가능한 요청값들의 범위`에 대해 고민해보고 메서드를 작성하겠습니다.

2024-02-23 11:56 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/option/Option.java
> +    public Option(final Long memberId, final Smoke smoke, final Religion religion,
수정 완료하였습니다!

2024-02-23 11:57 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/InfoController.java
> +
수정 완료하였습니다!

2024-02-23 12:23 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/StyleController.java
> +    public ResponseEntity<List<StyleSearchResponse>> findMemberStyles(@AuthMember Long memberId) {
수정 완료하였습니다!

2024-02-23 12:26 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/HobbyServiceTest.java
> +public class HobbyServiceTest {
수정하였습니다! 다른 클래스 코드들에서도 모두 제거하였습니다.

2024-02-23 12:39 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/HobbyServiceTest.java
> +@ExtendWith(MockitoExtension.class)
Mickito의 사용 이유는 when, verify 등 행위 검증을 할 때 정의해두기 위함인데, 말씀하신 대로 Fake를 이미 이용하기 때문에 없애도 될 것 같습니다. 수정 완료하였습니다.

2024-02-23 12:43 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +    ApplicationEvents events;
수정 완료하였습니다!

2024-02-23 12:46 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/ProfileServiceTest.java
> +            softly.assertThat(profileRepository.findByMemberId(memberId)).isPresent();
두 번째인 `softly.assertThat(profileRepository.findByMemberId(memberId)).isPresent();`만 남겨두는 식으로 수정 완료하였습니다.

2024-02-23 13:05 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/profile/year/YearManagerImpl.java
> +
말씀하신 게 맞습니다.. YearManager 구현체는 infrastructure, 인터페이스만 domain에 관리되도록 수정하였습니다.

2024-02-23 16:11 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    }
`from`은 정적 팩터리 메서드의 컨벤션이면서 동시에 "생성"하는 느낌이 있다면, 말씀하신 대로 `findBy`가 "조회"의 느낌을 주니 그게 더 좋은 듯 합니다.
마냥 네이밍 컨벤션을 무조건적으로 따르기보다는 `메서드의 본래 책임을 더 명확히 할 수 있는 이름은 없는지 고민`해보는 습관을 가져보겠습니다.

2024-02-23 16:32 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/profile/Position.java
> +    private double latitude;
`double`, `float`보다 `BigDecimal`이 더 미세한 숫자의 변동을 허용하지 않아 금융 등 민감한 데이터에서 다룸을 알았습니다.
위도 경도 또한 특정 거리만큼 집합을 만들거나 할 수 있기에 말씀하신대로 `BigDecimal`을 사용하는 것이 좋을 듯 합니다.
수정 완료하였습니다!

2024-02-23 16:44 UTC, devholic22 commented on src/main/java/com/atwoz/member/config/AuthConfig.java
> +                .addPathPatterns("/**", ANY);
일단 이렇게 하지 않으면 토큰을 주더라도 `로그인 정보를 찾을 수 없습니다` 예외가 발생해서 변경했었습니다.
하지만 말씀하신 내용을 보니, `인터셉터란 무엇인가?`에 대한 이해를 하지 않은 채 문제를 해결하려고 했던 것 같습니다.

인터셉터란 컨트롤러의 핸들러를 호출하기 전후 추가적인 작업을 원할 때 사용되는 것으로써, 현재 `ParseMemberIdFromTokenInterceptor`는 `LoginValidCheckerInterceptor`와 연계하여 사용자 정보를 인증하기 위해 사용됩니다.

따라서 전체 url에 대한 인터셉터에서, 현재 작업과 관련된 `/api/info/**` 로 변경 완료하였습니다.

2024-02-23 18:32 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/info/option/OptionRepositoryImpl.java
> +    }
수정 완료하였습니다. 성능에 대해 깊게 고민하지 않았던 것 같습니다.
추가로 [자료](https://fire-programmer.tistory.com/96)를 찾아보며 `COUNT(*)`가 가장 빠르게 수행된다는 것을 알게 되어 적용했습니다.

2024-02-24 02:09 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/OptionServiceTest.java
> +@ExtendWith(MockitoExtension.class)
서비스 테스트들에서 습관적으로 MockitoExtension을 붙인 것 같습니다. 삭제 완료하였습니다.

2024-02-24 02:29 UTC, devholic22 commented on src/test/java/com/atwoz/member/infrastructure/info/HobbyFakeRepository.java
> +        map.put(id, newHobby);
수정하였습니다. 추가로 Style 또한 null이 저장되지 않도록 변경했습니다.

2024-02-24 03:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/StyleController.java
> +                .toList();
`StyleSearchResponse(final Style style)`을 통해 DTO에서 변환하도록 수정했습니다! 더불어 `HobbySearchResponse`도 같은 맥락으로 수정 완료하였습니다.

2024-02-24 04:03 UTC, devholic22 commented on src/test/java/com/atwoz/member/ui/info/HobbyControllerWebMvcTest.java
> +    private OAuthArgumentResolver oAuthArgumentResolver;
수정 완료하였습니다! 다른 클래스들도 동일하게 변경하였습니다.

2024-02-24 09:11 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/StyleController.java
> +                .map(styleName -> new StyleSearchResponse(styleName.getName()))
아래처럼 DTO에서 변환하도록 수정 완료했습니다!

2024-02-24 09:19 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +        OptionWriteRequest optionWriteRequest = request.option();
동의합니다! `request.profile()`, `request.option()`으로만 주면 코드가 더 줄어들 수 있고 현재 별다른 작업을 수행하지 않으니 말씀하신 게 맞다고 생각됩니다. 수정 완료하였습니다

2024-02-24 09:19 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +                .toList();
수정 완료하였습니다!

2024-02-24 10:27 UTC, devholic22 commented on src/test/java/com/atwoz/member/ui/info/HobbyControllerWebMvcTest.java
> +        when(authArgumentResolver.resolveArgument(any(), any(), any(), any())).thenReturn(memberId);
완료했습니다!

2024-02-24 11:29 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/dto/InfoWriteRequest.java
> +
* 위에서 말씀하신 것 처럼 공백을 삭제하였습니다.
* validation을 넣지 않으니 하위 DTO 자체를 넣지 않았을 때 NPE가 발생함을 알았습니다. validation을 추가하였습니다!

2024-02-24 11:46 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/option/OptionService.java
> +    private boolean isMemberOptionExist(final Long memberId) {
수정 완료했습니다! 말씀하신대로 메서드 호출인데 굳이 분리할 필요가 없었네요..

2024-02-25 06:08 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/hobby/HobbyName.java
> +    GAME("PC · 모바일 게임"),
프론트에서 전달할 코드를 기준으로 조회되도록 수정하였고, Style, Job도 동일한 기준으로 조회되도록 수정하였습니다.

2024-02-25 06:59 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/profile/Body.java
> +            throw new ProfileRangeException();
ProfileRangeException을 삭제하고 AgeRangeException, HeightRangeException, LatitudeRangeException, LongitudeRangeException으로 세분화하였습니다.

2024-02-25 09:27 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/InfoController.java
> +        return ResponseEntity.ok()
수정 완료하였습니다.

2024-02-26 12:17 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/auth/TokenProvider.java
> +    String extract(final String token);
직접 바꿨었습니다. `createTokenWith` 메서드에서 claims로 id가 아니라 email만 담고 있기 때문에, Long id를 이끌어낼 수 없다고 판단했습니다.

2024-02-26 12:19 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/auth/interceptor/LoginValidCheckerInterceptor.java
> +                .orElseThrow(RuntimeException::new);
토큰에 id가 담기려면 `createTokenWith`에서 id가 인자로 전달되어야 하는데, email로 전달되어 있습니다.
만약 `createTokenWith` 메서드에서 id 값이 제공된다면 원래 작성하신대로 해도 될 것 같습니다.
다만 지금 기능을 개발할 때는 소셜 로그인이 email만 제공할 수 있다고 이해했어서 구조를 바꾸었었습니다.

2024-02-26 12:33 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/profile/ProfileService.java
> +    private final ProfileFactory profileFactory;
* 빈으로 등록할 필요가 없는 것에 동의합니다. (원래 의도는 정적 메서드로 만들고자 했는데, 컴포넌트로 등록해버린 것 같습니다.)
* Factory 자체의 필요성에 대해서는 Profile을 생성하는 단계가 너무 많다 보니 (Body를 만들고, Location을 만드는 등) 바로 요청 dto를 엔티티로 변환해주는 별도의 클래스가 있는 게 좋겠다는 생각이 들어 만든 것이었는데, (ProfileService에서 dto를 엔티티로 만든다면 내부적으로 많은 메서드가 필요할 것으로 예상했었습니다.) 혹시 재윤님은 Factory를 보통 어떨 때 만드시는지 여쭤봐도 될까요?

2024-02-27 06:38 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +    }
`@Autowired`가 있었음에도 `@BeforeEach`를 이용하여 또 할당하였었습니다. 수정하였습니다.

2024-02-27 06:41 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +@SpringBootTest
* 통합 테스트 시 RANDOM PORT를 설정하는 이유는 테스트 간 격리를 위해서입니다. (포트 충돌 방지) 또한 애플리케이션을 실행하고 있을 시점에 테스트를 돌릴 때에도 기본 포트 (8080)와 충돌되지 않기 위해 사용하기도 합니다.
* InfoServiceTest에서는 이벤트 발생을 검증하기 위해 `RecordApplicationEvents`를 사용해야 하는데, 이것은 스프링 컨텍스트에서 제공받아야 합니다. 따라서 `@SpringBootTest`가 없을 때 이벤트 검증을 시도한다면 ApplicationEvents의 값에 대해 NullPointerException이 발생해서 `@SpringBootTest`를 붙였었습니다.

2024-02-27 06:41 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/StyleController.java
> +                .toList();
`StyleSearchResponse.from` 메서드를 만듦으로써 수정하였습니다.

2024-02-27 06:45 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +        OptionWriteRequest optionWriteRequest = request.option();
생각해보니 말씀하신대로 굳이 변수로 추출할 필요가 없었던 것 같습니다. 이벤트에 바로 넘기는 방식으로 수정하였습니다.

2024-02-27 07:10 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/profile/year/YearManager.java
> +public interface YearManager {
YearManager의 사용을 도메인에서 하도록 수정하였습니다. (생성자에 인터페이스 전달)

2024-02-27 07:11 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/option/OptionFactory.java
> +@Component
* ProfileFactory처럼 Option을 생성하는 데 책임이 있습니다.
* 같은 이유로 빈 등록을 해제하였습니다. 단순 생성인만큼 정적 메서드로 사용해도 충분했는데 사용을 잘못했었습니다.

2024-02-27 08:35 UTC, devholic22 commented on src/test/java/com/atwoz/member/fixture/info/BodyFixture.java
> +    private static final int HEIGHT = 171;
다른 클래스들과의 통일성을 생각하지 못했었습니다. 다른 메서드들처럼 변수로 할당해주는 게 좋을 것 같아 수정하였습니다.

2024-02-27 09:47 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +        );
Fixture 작성 완료하였습니다!

2024-02-27 14:45 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +
* 공백 제거 완료하였습니다.
* Fixture를 둠으로써 해결하였습니다.

2024-02-27 15:47 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/ProfileServiceTest.java
> +            softly.assertThat(profileRepository.findByMemberId(memberId).get()).isEqualTo(expectedProfile);
`usingRecursiveComparison`을 사용하여 수정 완료하였습니다.

2024-02-28 06:55 UTC, devholic22 commented on src/main/java/com/atwoz/member/domain/info/hobby/Hobby.java
> +public class Hobby {
수정 완료하였습니다! 말씀하신대로 MemberHobby로 해야 Member와 Hobby의 구조인 것을 더 쉽게 알 수 있다고 생각합니다 :)

2024-02-28 10:36 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +@ExtendWith(MockitoExtension.class)
* MockitoExtension: 앞서 말씀드린대로 잘못 작성했었던 것 같습니다.. (mocking을 할 필요가 없는데 붙였었습니다.)
* RecordApplicationEvents: 이벤트 발생을 시키기 때문에 이벤트 발생 횟수를 검증하기 위해 적용하였습니다.
* SpringBootTest: 서비스 테스트이긴 하나, ApplicationEvents를 할당받기 위해서는 SpringBootTest를 붙여야 NullPointerException이 발생하지 않는다는 것을 알게 되어 적용했습니다.

2024-02-28 16:03 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/option/OptionService.java
> +    public void writeOption(final Long memberId, final OptionWriteRequest request) {
수정 완료하였습니다!

2024-02-28 16:04 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/hobby/HobbyService.java
> +        deleteMemberHobbies(memberId);
수정 완료하였습니다! 생성과 수정을 동일한 메서드로 이용하도록 했던 판단때문에 이렇게 설계했던 것 같습니다.

2024-02-28 16:05 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/hobby/HobbyService.java
> +    public void deleteMemberHobbies(final Long memberId) {
단순 메서드 호출은 메서드로 나눌 필요가 없는 게 가독성 측면에서 더 낫다는 것을 다시 깨달았습니다..
접근제어자를 public으로 했던 이유는 `@Transactional` 때문이었는데, 이 또한 메서드를 나누지 않았다면 고민하지 않았던 부분인 것 같습니다. 수정 완료하였습니다!

2024-02-29 03:18 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/HobbyController.java
> +public class HobbyController {
* Querydsl을 활용함으로써 InfoController를 제외한 나머지 컨트롤러들을 모두 삭제 완료하였습니다.
* 다만 서비스는 만약 서비스를 나누지 않을 경우 InfoService에서 모든 리포지터리 (Profile, Option, MemberHobby, MemberStyle)에 대해 의존하고 작업을 수행해야 하는데, 그러기보다는 이벤트로 복잡성을 분리하는 게 더 낫겠다는 생각을 했었습니다.

2024-02-29 04:07 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/profile/ProfileFactory.java
> +    }
* 처음에는 전달되는 인자 타입이 ProfileWriteRequest의 내부 타입들이기에 이들을 분리하는 것이 좋겠다는 생각을 했었습니다. (`profileWriteRequest.position().latitude()` 이런 식으로 작성하지 않고자 함이었습니다.)
* 하지만 말씀하신대로 메서드가 너무 많이 분리되는 것 같아 하나의 메서드에서 처리하도록 수정하였습니다.

2024-02-29 04:13 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +        assertSoftly(softly -> {
`모든_정보를_조회한다()`를 통해 검증하는 방식으로 수정하였습니다.

2024-02-29 10:18 UTC, sosow0212 requested changes
수고하셨습니다 몇 부분 확인하고 계층구조랑 코드 스타일 조금만 더 신경써주세요~ 고생하셨습니다잉

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/option/OptionWriteRequest.java
> +public class OptionWriteRequest implements OptionRequest {
OptionUpdateRequest랑 완전 똑같은 클래스네요

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/option/OptionRequest.java
> +public interface OptionRequest {
인터페이스로 나눈 이유가 있나요?
OptionUpdateRequest 같은 곳에서는 해당 메서드를 오버라이드 하지도 않는 것 같아보이고 나눈 이유가 있나 궁금해요

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/profile/location/LocationRequest.java
> +public interface LocationRequest {
이 부분도 그렇고 다른 부분 모두 왜 인터페이스로 분리를 한 건가요??

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/hobby/MemberHobbyService.java
> +    public void updateMemberHobbies(final Long memberId, final List<String> hobbyCodes) {
변경감지로 업데이트 할 수 있지 않을까요? 쿼리 문제도 그렇고, 도메인 로직을 외부에서 처리하는 것처럼 보이네요!

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/event/info/StyleWroteEvent.java
> +public class StyleWroteEvent extends Event {
파일체인지에 보이지가 않아서 여기에 남깁니다!
application/event 안에 ValidatedLoginEvent는 패키지 참조가 잘못 되어 있는 것 같아요
그리고 이벤트의 패키지는 어디로 가는게 좋을까요?

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/option/OptionFactory.java
> +    public static Option createOption(final Long memberId, final OptionRequest optionRequest) {
도메인에서 처리하면 되는데 Factory 클래스를 만든 이유가 있나요?

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/profile/ProfileService.java
> +        );
이 부분도 Factory보다 도메인에서 처리하는게 나아보입니다
굳이 객체를 새로 생성하고, 새로 생성한 객체의 값들을 기존 값에 덮어쓰고 있는 것 같은데, 이렇게 되면 update하는 도메인 로직은 결국 외부인 Factory로직에 의존하는 거가 되는 것 같습니다

Factory를 사용하지 말던가, 아니면 사용하고 싶다면 도메인 안에서 사용하는게 낫지 않을까요?

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/profile/location/LocationUpdateRequest.java
> +        @NotBlank(message = "시/도가 작성되어야 합니다.")
여긴 정렬이 이상한 것 같습니다!

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/profile/location/LocationWriteRequest.java
> +        @NotBlank(message = "시/도가 작성되어야 합니다.")
여기도 정렬이 이상하네요

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/dto/profile/location/LocationWriteRequest.java
> +        @NotBlank(message = "시/도가 작성되어야 합니다.")
밑에 다른 부분도 이상한 부분이 많은데 확인 부탁드립니다

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/application/info/style/MemberStyleService.java
> +    public void updateMemberStyles(final Long memberId, final List<String> styleCodes) {
이 부분도 도메인에서 변경감지로 처리되어야하는데 외부에서 처리가 되네요 ㅠㅠ

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/infrastructure/info/hobby/MemberHobbyRepositoryImpl.java
> +        memberHobbyJpaRepository.saveAll(memberHobbies);
다른 부분도 그렇지만, memberHoobyJpaRepository에 해당 메서드들을 만들어줘야하지 않을까요? 기본 메서드가 있더라도 명시해주면 좋은 이유는 무엇일까요?

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/info/dto/HobbySearchResponse.java
> +
불필요한 공백이 있습니다

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/ui/info/dto/profile/ProfileSearchResponse.java
> +
굳이 중간 공백은 없어도 될 것 같습니다!

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/infrastructure/info/InfoRepositoryImpl.java
> +                .where(QOption.option.memberId.eq(memberId))
.orElseThrow는 서비스에서 처리해줘야할 것 같습니다

2024-02-29 10:18 UTC, sosow0212 commented on src/main/java/com/atwoz/member/infrastructure/info/InfoRepositoryImpl.java
> +    private Profile selectProfileByMemberId(final Long memberId) {
QueryDSL 사용하는 부분도 클래스로 분리하는게 좋을 것 같습니다

2024-02-29 10:18 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +        InfoWriteRequest infoWriteRequest = 정보_생성_요청();
무슨 정보인지 명시해주면 좋을 것 같습니다 나중에 많아지면 헷갈릴 것 같아요

2024-02-29 10:18 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/MemberHobbyServiceTest.java
> +class MemberHobbyServiceTest {
서비스에서 예외 검증이 하나도 안 되어있는데 이런 부분도 검증해주세요

2024-02-29 10:18 UTC, sosow0212 commented on src/test/java/com/atwoz/member/application/info/OptionServiceTest.java
> +        optionService.writeOption(memberId, writeRequest);
서비스에 다른 메서드가 바뀌면 해당 테스트는 변경될 것 같습니다
차라리 하위 계층인 repository를 이용하는 건 어떨까요?

2024-02-29 10:18 UTC, sosow0212 commented on src/test/java/com/atwoz/member/ui/auth/AuthControllerWebMvcTest.java
> +    private MemberRepository memberRepository;
이건 MockBeanInjection에 넣어야할 것 같아요

2024-02-29 10:18 UTC, sosow0212 commented on src/test/java/com/atwoz/member/ui/info/InfoControllerWebMvcTest.java
> +    private InfoService infoService;
이것도 MockBeanInjection에 넣어야합니다

2024-02-29 10:18 UTC, sosow0212 commented on src/test/java/com/atwoz/member/ui/info/InfoControllerWebMvcTest.java
> +    private InfoService infoService;
E2E 테스트도 진행해주세요~

2024-03-01 02:40 UTC, devholic22 commented on src/test/java/com/atwoz/member/ui/info/InfoControllerWebMvcTest.java
> +    private InfoService infoService;
수정하였습니다!

2024-03-01 02:46 UTC, devholic22 commented on src/test/java/com/atwoz/member/ui/auth/AuthControllerWebMvcTest.java
> +    private MemberRepository memberRepository;
MemberRepository 자체를 사용하지 않음을 발견하여, 삭제 조치하였습니다!

2024-03-01 02:50 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/dto/HobbySearchResponse.java
> +
수정 완료하였습니다

2024-03-01 02:51 UTC, devholic22 commented on src/main/java/com/atwoz/member/ui/info/dto/profile/ProfileSearchResponse.java
> +
수정 완료하였습니다! Request DTO에서 어노테이션 때문에 공백을 뒀어서 Response DTO에서도 습관적으로 공백을 둔 것 같습니다. 별도의 어노테이션이 없다면 공백을 제거해두도록 하겠습니다.

2024-03-01 04:56 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/InfoServiceTest.java
> +        InfoWriteRequest infoWriteRequest = 정보_생성_요청();
수정 완료하였습니다!

2024-03-01 18:44 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/dto/profile/location/LocationUpdateRequest.java
> +        @NotBlank(message = "시/도가 작성되어야 합니다.")
레코드로 만들었다가 클래스로 변환하는 과정에서 탭이 유지된 것 같습니다..! 레코드로 복구하였습니다.

2024-03-01 18:44 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/dto/profile/location/LocationWriteRequest.java
> +        @NotBlank(message = "시/도가 작성되어야 합니다.")
전부 레코드를 빠르게 클래스로 변환하려다보니 발생한 문제 같습니다.. 바로 수정하였습니다!

2024-03-01 18:52 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/hobby/MemberHobbyService.java
> +    public void updateMemberHobbies(final Long memberId, final List<String> hobbyCodes) {
이것과 관련해서는 고민점이 있습니다.
* MemberHobby, MemberStyle은 memberId와 Hobby / Style이 M:N으로 되어 있는 구조입니다.
* 그렇기 때문에 변경 감지를 하기 위해서는, 기존에 저장된 내역과 새로 들어온 요청들을 하나씩 검사하면서 아래 경우의 수가 존재하게 됩니다.
  * `회원의 취미/스타일 갯수` > `새로 들어온 (수정할) 취미/스타일 갯수`
    * 이 때는 새로 들어온 갯수만큼 변경 감지를 이용하고, (회원의 취미/스타일 갯수) - (새로 들어온 취미/스타일 갯수)만큼 삭제 쿼리가 발생합니다.
  * `회원의 취미/스타일 갯수` = `새로 들어온 (수정할) 취미/스타일 갯수` (이 때는 말씀하신 변경 감지를 이끌어낼 수 있을 듯 합니다.)
  * `회원의 취미/스타일 갯수` < `새로 들어온 (수정할) 취미/스타일 갯수`
    * 이 때는 저장된 갯수만큼 변경 감지를 이용하고, (새로 들어온 취미/스타일 갯수) - (회원의 취미/스타일 갯수)만큼 추가 쿼리가 발생합니다.
* 이렇듯 변경 감지를 위해서는 세 가지에 대해서 각각 구현을 하고, 그렇기에 복잡도가 올라간다는 생각이 들었습니다.
* 그 대신, 기존에 `updateMemberHobbies`를 할 때 작성했던 `deleteHobbiesByMemberId` 메서드가 저장되었던 `취미 갯수만큼 각각 delete` 쿼리가 일어났던 문제를 `@Query("delete from MemberHobby mh where mh.memberId = :memberId")`로 한 번에 삭제하도록 수정했는데, 이런 방식으로 이끌어나가도 될 지 여쭤드립니다..!

2024-03-01 19:03 UTC, devholic22 commented on src/test/java/com/atwoz/member/ui/info/InfoControllerWebMvcTest.java
> +    private InfoService infoService;
작성 완료하였습니다! 처음 작성해 본 E2E 테스트인데, 고칠 점이 있다면 바로 반영하겠습니다 :)

2024-03-02 02:17 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/info/InfoRepositoryImpl.java
> +    private Profile selectProfileByMemberId(final Long memberId) {
수정 완료하였습니다!

2024-03-02 02:32 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/info/InfoRepositoryImpl.java
> +                .where(QOption.option.memberId.eq(memberId))
수정 완료하였습니다! 조인하는 과정 때문에 리포지터리에서 하는 것으로 생각했었던 것 같습니다.

2024-03-02 06:14 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/OptionServiceTest.java
> +        optionService.writeOption(memberId, writeRequest);
무슨 말씀인지 이해하였습니다! 서비스 테스트인데 다른 메서드를 먼저 호출할 경우 의도치 않게 바뀔 수 있다는 것을 놓쳤었습니다
수정 완료하였습니다

2024-03-02 06:47 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/option/OptionFactory.java
> +    public static Option createOption(final Long memberId, final OptionRequest optionRequest) {
인자가 많거나 구현 로직이 복잡한 경우 Factory를 사용하려는 취지로 접근했었습니다.
말씀하신 뒤 Factory에 대해서 생각을 다시 하게 되었고, 그 대신 `정적 팩터리 메서드`로 대체하였습니다.
정적 팩터리도 인자가 너무 많은 것 같아 쓰지 않는 게 낫겠다는 생각을 했었는데, 다시 생각해보니 객체에게 책임을 더 부여해줄 수 있다는 게 느껴져서 수정하였습니다.
가급적 Factory를 사용하지 않는 방향으로 작성하겠습니다..!

2024-03-03 02:54 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/profile/ProfileService.java
> +        );
도메인 전용 DTO를 사용하는 방식으로 수정 완료하였습니다!

2024-03-03 14:00 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/event/info/StyleWroteEvent.java
> +public class StyleWroteEvent extends Event {
이벤트 패키지에 대해 다시 고민을 해 보니, 자신이 처리하는 곳에 더 가깝게 위치하는 것이 낫겠다는 생각을 하였습니다.
예시로 `application/profile/dto`로 profileService가 필요로 하는 dto가 위치해 있듯이, `application/profile/event`로 두면 자신과 관련된 이벤트들이 동일한 패키지들이 묶여 더 합리적인 구조를 만들 수 있겠다고 생각하여 수정하였습니다.

2024-03-03 17:00 UTC, devholic22 commented on src/test/java/com/atwoz/member/application/info/MemberHobbyServiceTest.java
> +class MemberHobbyServiceTest {
수정 완료하였습니다! 스타일도 동일하게 적용하였습니다.

2024-03-03 17:14 UTC, devholic22 commented on src/main/java/com/atwoz/member/infrastructure/info/hobby/MemberHobbyRepositoryImpl.java
> +        memberHobbyJpaRepository.saveAll(memberHobbies);
`인터페이스의 존재 목적`을 더 명확히 하기 위해서라고 생각됩니다.
save, saveAll 등 기본 메서드들은 상위 인터페이스인 JpaRepository, CrudRepository 등에 내장되어 있는데, 이렇게 되면 개발자가 사용하게 되는 인터페이스인 OptionJpaRepository 등에서는 서비스에서 사용하고자 하는 규약 중 일부가 감춰져 있기 때문에 혼동을 줄 수도 있겠다는 생각이 들었습니다.

리포지터리들에 메서드들을 작성하는 방식으로 수정하였습니다!

2024-03-05 03:39 UTC, eom-tae-in approved these changes
고생하셨습니다

2024-03-05 03:39 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +import com.atwoz.member.ui.info.dto.InfoSearchResponse;
역참조가 발생하는데 구조 변경이 필요해보입니다.

2024-03-05 03:39 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +    }
request.styles().stream(), request.hobbies().stream()이 한 맥락인데 매개변수를 InfoWriteRequest로 받는 이유가 있나요?
한 줄에 체이닝을 한번 사용하기 위해 일부러 분리한 것 처럼 보이네요
request를 넘기지 말고 값을 꺼내서 넘기도록 수정해주세요~

2024-03-05 03:39 UTC, eom-tae-in commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +    }
이것도 request 값 꺼내서 넘겨주세요~

2024-03-05 03:45 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +    }
수정하였습니다 :)

2024-03-05 03:45 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +    }
값을 한번 꺼내서 넘기면 불필요한 체이닝을 제거할 수 있겠군요..! 수정 완료하였습니다 :)

2024-03-05 03:45 UTC, devholic22 commented on src/main/java/com/atwoz/member/application/info/InfoService.java
> +import com.atwoz.member.ui.info.dto.InfoSearchResponse;
InfoSearchResponse의 역참조를 없애기 위해 Infrastructure로 옮기는 방식으로 해결하였습니다!

2024-03-05 05:42 UTC, sosow0212 approved these changes
태인이가 말한 부분 고쳐주시면 될 것 같습니다.
작업하시느라 수고하셨습니다~

2024-03-05 07:47 UTC, merged